### DISCUSSION TITLE
advanced daemonset灰度更新编排

### DISCUSSION THREAD

**Discussion by aeinrw** [openkruise/kruise#1417] [Ideas]
现阶段advanced daemonset的已经支持灰度更新策略，但只能依靠黑屏操作，人工去更新partition、labelSelector字段，多次灰度变更需要多次操作，依赖人工操作。1000个节点的集群，每次更新50台节点，就需要手动操作20次。

现在有一个需求是直接将灰度变更的过程自动化，想法是增加一个plan字段，将灰度过程分为多个过程，定时将plan中的selector和partition字段更新到rollingUpdate中，并等待interval的时间。通过这样实现灰度更新编排，解放人力。

想请社区的各位大佬评估一下这样的做法是否合适，或者是否有其他的方法完成这样的灰度更新编排功能。

```yaml
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      selector: ...
      partition: ...
    plan: 
    - selector: ...
      partition: 900
      interval: 40m
    - selector: ...
      partition: 600
      interval: 5m
    - selector: ...
      partition: 300
      interval: 5m
    - selector: ...
      partition: 0
```
