### DISCUSSION TITLE
WorkloadSpread pod deletion cost calculate question

### DISCUSSION THREAD

**Discussion by FarmerChillax** [openkruise/kruise#2042] [Q&A]
I am testing workloadSpread to calculate the deletion cost and encountered a write doubt.

`WorkloadSpread.yaml` setting:
```
apiVersion: apps.kruise.io/v1alpha1
kind: WorkloadSpread
metadata:
  name: nginx
spec:
  scheduleStrategy:
    adaptive:
      rescheduleCriticalSeconds: 2
    type: Adaptive
  subsets:
    - name: static-resource-pool
      patch:
        metadata:
          labels:
            resource-pool: static
    - name: dynamic-resource-pool
      patch:
        metadata:
          labels:
            resource-pool: dynamic
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
```

workload setting:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 20
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: resource-pool
                    operator: In
                    values:
                      - static
            - weight: 50
              preference:
                matchExpressions:
                  - key: resource-pool
                    operator: In
                    values:
                      - dynamic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
```

node label:
```
| node name | label |
| kind-control-plane | <basicLabels>  |
| kind-worker | resource-pool=static |
| kind-worker2 | resource-pool=dynamic |
```

Phenomenon:
```
| pod name | node | pod-deletion-cost |
| nginx-5d795b6c9b-55dsr |  kind-worker  | 200 |
| nginx-5d795b6c9b-bgqzc | kind-worker | 200 |
| nginx-5d795b6c9b-nnnjr | kind-worker2 | 200 |
```

expect:
```
| pod name | node | pod-deletion-cost |
| nginx-5d795b6c9b-55dsr |  kind-worker  | 200 |
| nginx-5d795b6c9b-bgqzc | kind-worker | 200 |
| nginx-5d795b6c9b-nnnjr | kind-worker2 | 100 |
```

Question:
Why do `kind-worker` and `kind-worker2` have the same score?
