### ISSUE TITLE
[feature request] need webhook validation for perserve-unknown fields like pod template

### ISSUE THREAD

**Issue by gotosre** [openkruise/kruise#1000]
k8 ver: 1.18
kruise ver: 1.2.0

manifest:

```
    spec:
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Delete
```

but when apply(create)

manifest become default value 
```
    spec:
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain
```

when i edit it with kubectl edit

it become as expected

```
    spec:
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Delete
```
