### ISSUE TITLE
[BUG] sidecar不更新 

### ISSUE THREAD

**Issue by direct-spl** [openkruise/kruise#1003]
更新sidecar配置或者镜像后，sidecar一直未更新
```
[root@szvpk8s00017 ~]# kubectl get sidecarsets.apps.kruise.io 
NAME      MATCHED   UPDATED   READY   AGE
sandbox   16        1         16      17m
[root@szvpk8s00017 ~]# kubectl get sidecarsets.apps.kruise.io 
NAME      MATCHED   UPDATED   READY   AGE
sandbox   16        1         16      17m
[root@szvpk8s00017 ~]#
```

**Comment by veophi** [comment]
Plz show your sidecarset configuration
` kubectl get sidecarset -oyaml | grep partition`

**Comment by direct-spl** [comment]
> Plz show your sidecarset configuration ` kubectl get sidecarset -oyaml | grep partition`
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sandbox
  namespace: fgamma
spec:
  selector:
    matchLabels:
      sidecar: fgamma
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
    # shareProcessNamespace: true 
  namespace: fgamma
  containers:
  - name: sandbox
    image: hub.hwht.com/smartcom/sandbox:1.0.5
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    shareVolumePolicy:
      type: enabled
```
