### ISSUE TITLE
[BUG] No effect when the `BroadcastJob` spec is changed and applied again

### ISSUE THREAD

**Issue by astraw99** [openkruise/kruise#1033]
**What happened**:
Firstly apply a `BroadcastJob` yaml to the cluster, we can see the job pod `Completed`.
Then change the spec and apply to the cluster, the controller take no effect as if nothing happened.

**What you expected to happen**:
When the `BroadcastJob` spec was changed, the controller shoud reconcile again to take the spec into effect.
If the `BroadcastJob` spec is allowed to change, then it should take effect immediately.

> By the way, the offcial K8s `Job` spec is not allowed to change after it is applied.

**How to reproduce it (as minimally and precisely as possible)**:
1. Apply a `BroadcastJob` yaml to the cluster, see the job `Completed`.
```
apiVersion: apps.kruise.io/v1alpha1
kind: BroadcastJob
metadata:
  name: broadcastjob-never-complete
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: busybox
          command: ["sleep",  "5"]
      restartPolicy: Never
  completionPolicy:
    type: Never
```
2. Change the `containers.command` to `["sleep",  "10"]`, apply it.
3. Check there is no working job pod according to the newly applied spec.

**Environment**:
- Kruise version: 1.2.0
- Install details (e.g. helm install args): helm install kruise openkruise/kruise --version 1.2.0
