### ISSUE TITLE
[BUG] BroadcastJob not running to completion when completion policy is set to Always

### ISSUE THREAD

**Issue by lepolesaLibete** [openkruise/kruise#1039]
**What happened**:
I am running BroadcastJob through AdvanceCronjob. I set completion policy as below. What I see is that after all pods run to completion, the  new BroadcastJob is started immediately after the scheduled one completes and this behaviour just keeps on going.
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: AdvancedCronJob
metadata:
  name: my-advance-cronjob
spec:
  schedule: 0 18,06 * * *
  template:
    broadcastJobTemplate:
      spec:
        template:
          spec:
            containers:
             ...
            restartPolicy: Never
        parallelism: 15
        completionPolicy:
          type: Always
          ttlSecondsAfterFinished: 5
          activeDeadlineSeconds: 3600
```

**What you expected to happen**:
I expected the BroadCastJob to start at the give schedule time and run to completion until the next schedule.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: v1.2
- Kubernetes version (use `kubectl version`): version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-a64ea69", GitCommit:"03450cdabfc4162d4e447e6d8c5037efe6d29742", GitTreeState:"clean", BuildDate:"2022-05-12T18:44:04Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
- Install details (e.g. helm install args): default helm values
- Others:
