### ISSUE TITLE
[BUG] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by a33151** [openkruise/kruise#1098]
**What happened**:

根据官方demo

# 优先部署到基础节点池，资源不足再部署到弹性资源池
```
配置如下： 
scheduleStrategy:
  type: Adaptive
  adaptive:
    rescheduleCriticalSeconds: 30
    disableSimulationSchedule: false
subsets:
- name: subset-normal #副本数量不限
  requiredNodeSelectorTerm:
    matchExpressions:
    - key: app.deploy/zone
      operator: In
      values:
      - normal
- name: subset-elastic #副本数量不限
  requiredNodeSelectorTerm:
    matchExpressions:
    - key: app.deploy/zone
      operator: In
      values:
      - elastic
```
我这边配置两个资源池 一个是common 一个是spot 。
 但是当    maxReplicas: 10%  不配置比例时， 无法apply WorkloadSpread，查看日志

```

报错：
for: "workload-spot.yaml": Internal error occurred: failed calling webhook "vworkloadspread.kb.io": Post "https://kruise-webhook-service.kruise-system.svc:443/validate-apps-kruise-io-v1alpha1-workloadspread?timeout=30s": EOF

日志：

2022-10-08 04:12:24.959576 I | http: panic serving 10.55.22.33:34858: runtime error: invalid memory address or nil pointer dereference
goroutine 18505 [running]:
net/http.(*conn).serve.func1(0xc004076280)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x1abf440, 0x2b98a90)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/openkruise/kruise/pkg/webhook/workloadspread/validating.validateWorkloadSpreadSubsets(0xc002e7b1d0, 0x2, 0x2, 0xc0040be960, 0x0, 0x0
, 0xc0040be960)
        /workspace/pkg/webhook/workloadspread/validating/workloadspread_validation.go:244 +0x865
github.com/openkruise/kruise/pkg/webhook/workloadspread/validating.validateWorkloadSpreadSpec(0xc0047d5980, 0xc0040be930, 0x0, 0x0, 0x0)
        /workspace/pkg/webhook/workloadspread/validating/workloadspread_validation.go:119 +0x237
github.com/openkruise/kruise/pkg/webhook/workloadspread/validating.(*WorkloadSpreadCreateUpdateHandler).validatingWorkloadSpreadFn(0xc0000b09e0
, 0xc0047d5980, 0x24, 0xc0041cf180, 0xe)
        /workspace/pkg/webhook/workloadspread/validating/workloadspread_validation.go:67 +0x74
github.com/openkruise/kruise/pkg/webhook/workloadspread/validating.(*WorkloadSpreadCreateUpdateHandler).Handle(0xc0000b09e0, 0x1f9aa00, 0xc002d
cb000, 0xc002d72d80, 0x24, 0xc0041cf180, 0xe, 0xc0041cf178, 0x8, 0xc0041cf190, ...)
        /workspace/pkg/webhook/workloadspread/validating/workloadspread_create_update_handler.go:55 +0x834
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(0xc0007ace40, 0x1f9aa00, 0xc002dcb000, 0xc002d72d80, 0x24, 0xc0041cf180,
 0xe, 0xc0041cf178, 0x8, 0xc0041cf190, ...)
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:135 +0xb5
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc0007ace40, 0x7fe18e174cd0, 0xc002f23a90, 0xc001935f00)
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:87 +0xb38
```

```
apiVersion: apps.kruise.io/v1alpha1
kind: WorkloadSpread
metadata:
  name: test-demo
  namespace: test-product
spec:
  targetRef:
    apiVersion: apps.kruise.io/v1alpha1
    kind: CloneSet
    name: test-project-test-cp1
  subsets:
  - name: pool-common
    maxReplicas: 10%
    requiredNodeSelectorTerm:
      matchExpressions:
      - key: biz.type
        operator: In
        values:
        - common
    patch:
      metadata:
        labels:
            biz.type1: common
  - name: pool-spot
    requiredNodeSelectorTerm:
      matchExpressions:
      - key: biz.type
        operator: In
        values:
        - spot
    patch:
      metadata:
        labels:
            biz.type1: spot
  scheduleStrategy:
    type: Adaptive
    adaptive:
      rescheduleCriticalSeconds: 120
      disableSimulationSchedule: false
```
请问 maxReplicas 是必须设置的吗，还是我这边使用的方式有问题。

感谢！

**Environment**:
- Kruise version: v 0.10.2
- Kubernetes version (use `kubectl version`):   1.20.10
- Install details (e.g. helm install args): heml install 
- Others:
