### ISSUE TITLE
[BUG] The container cannot use the envFrom configuration item

### ISSUE THREAD

**Issue by pengln** [openkruise/kruise#1103]
**What happened**:
I traced the logs of kruise-controller-managerPOD, and kruise-controller-manager gives the following error: 
```text
I1019 08:05:26.238822       1 event.go:282] Event(v1.ObjectReference{Kind:"StatefulSet", Namespace:"test", Name:"test-echoserver", UID:"7bea180f-b251-4aa4-a1ce-1d76a5cb63ed", APIVersion:"apps.kruise.io/v1beta1", ResourceVersion:"396885", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' create Pod test-echoserver-1 in StatefulSet test-echoserver failed error: Pod "test-echoserver-1" is invalid: spec.containers[2].envFrom: Invalid value: "": must specify one of: `configMapRef` or `secretRef`
```
**What you expected to happen**:
I use envFrom for one of the container configurations in the multi-container POD, and configure the corresponding configMapRef, but when I create the POD, the POD is not created. 

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-game-config
  namespace: test
data:
  EVDATA="100"
  EVAGE="1.2"
---
apiVersion: apps.kruise.io/v1beta1
kind: StatefulSet
metadata:
  name: test-echoserver
  namespace: test
spec:
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  reserveOrdinals:
  - 0
  replicas: 1
  selector:
    matchLabels:
      app: test-echoserver
  template:
    metadata:
      labels:
        app: test-echoserver
    spec:
      shareProcessNamespace: true
      readinessGates: 
      - conditionType: InPlaceUpdateReady
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 21780
        env:
        - name: PORT
          value: "21780"
        volumeMounts:
        - name: test-persistent-storage
          mountPath: /data
      - image: debian:11
        imagePullPolicy: IfNotPresent
        name: shell
        envFrom:
        - configMapRef:
          name: test-game-config
        command: [ "bash" ]
        stdin: true
        tty: true
```
**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.3
- Kubernetes version (use `kubectl version`): 1.25
- Install details (e.g. helm install args): helm install kruise openkruise/kruise --version 1.3.0 
- Others:
