### ISSUE TITLE
[BUG] StatefulSet adjusting replicas will cause reserveOrdinals to fail

### ISSUE THREAD

**Issue by pengln** [openkruise/kruise#1104]
**What happened**:
StatefulSet adjusting replicas will cause reserveOrdinals to fail

**What you expected to happen**:
Create a StatefulSet type POD, then use --replicas=0 to stop the POD, use --replicas=1 again to start the POD, the id of the POD will start from 0, the reserveOrdinals

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: apps.kruise.io/v1beta1
kind: StatefulSet
metadata:
  name: test-echoserver
  namespace: test
spec:
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  reserveOrdinals:
  - 0
  replicas: 1
  selector:
    matchLabels:
      app: test-echoserver
  template:
    metadata:
      labels:
        app: test-echoserver
    spec:
      shareProcessNamespace: true
      readinessGates: 
      - conditionType: InPlaceUpdateReady
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 21780
        env:
        - name: PORT
          value: "21780"
      - image: debian:11
        imagePullPolicy: IfNotPresent
        name: shell
        envFrom:
        - configMapRef:
          name: test-game-config
        command: [ "bash" ]
        stdin: true
        tty: true
```

**Anything else we need to know?**:
After creating the StatefulSet, use edit to edit the created Statefulset, you will find the reserveOrdinals are lost.

**Environment**:
- Kruise version: 1.3.0
- Kubernetes version (use `kubectl version`): 1.25
- Install details (e.g. helm install args): helm install kruise openkruise/kruise --version 1.3.0
- Others:
