### ISSUE TITLE
[BUG] 安装部署不成功的问题

### ISSUE THREAD

**Issue by CraneRZz** [openkruise/kruise#1117]
**What happened**:

我使用helm安装部署了kruise，但pod一直处于循环崩溃的状态。我查看了pod日志，主进程好像崩溃了。

下面是pod日志的截图

<img width="1699" alt="image" src="https://user-images.githubusercontent.com/44353101/200516187-c3e52ac3-f11a-4f88-bd69-3bc437d195db.png">

**Environment**:
- Kruise version:1.3.0
- Kubernetes version (use `kubectl version`):v1.22.15
- Install details (e.g. helm install args):

 ```
   $ helm repo add openkruise https://openkruise.github.io/charts/
    $ helm repo update
    $ helm install kruise openkruise/kruise --version 1.3.0
```

- Others: helm v3.10.0

**Comment by zmberg** [comment]
看报错是没有找到 dockershim.sock 文件，能 ls 看一下你的 /hostvarrun 目录下有哪些文件吗？

**Comment by zmberg** [comment]
dockershim.sock 文件是由kubelet创建的，既然你是docker，这个文件也是必须的。所以，看看你的kubelet配置是如何的？

**Comment by CraneRZz** [comment]
> dockershim.sock 文件是由kubelet创建的，既然你是docker，这个文件也是必须的。所以，看看你的kubelet配置是如何的？

好的，这是我的kubelet配置：
```
# cat /var/lib/kubelet/config.yaml

apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: systemd
cgroupsPerQOS: true
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
configMapAndSecretChangeDetectionStrategy: Watch
containerLogMaxFiles: 5
containerLogMaxSize: 10Mi
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
cpuCFSQuotaPeriod: 100ms
cpuManagerPolicy: none
cpuManagerReconcilePeriod: 10s
enableControllerAttachDetach: true
enableDebuggingHandlers: true
enableProfilingHandler: true
enableServer: true
enableSystemLogHandler: true
enforceNodeAllocatable:
- pods
eventBurst: 10
eventRecordQPS: 5
evictionHard:
  imagefs.available: 15%
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
evictionPressureTransitionPeriod: 5m0s
failSwapOn: true
fileCheckFrequency: 20s
hairpinMode: promiscuous-bridge
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 20s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
iptablesDropBit: 15
iptablesMasqueradeBit: 14
kind: KubeletConfiguration
kubeAPIBurst: 10
kubeAPIQPS: 5
logging: {}
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxPods: 110
memorySwap: {}
nodeLeaseDurationSeconds: 40
nodeStatusMaxImages: 50
nodeStatusReportFrequency: 10s
nodeStatusUpdateFrequency: 10s
oomScoreAdj: -999
podPidsLimit: -1
port: 10250
registryBurst: 10
registryPullQPS: 5
resolvConf: /run/systemd/resolve/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 2m0s
serializeImagePulls: true
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
volumeStatsAggPeriod: 1m0s
```
