### ISSUE TITLE
[BUG] 启用annotations注入白名单失败

### ISSUE THREAD

**Issue by itcai** [openkruise/kruise#1138]
**What happened**:
使用SidecarSet对pod进行注入annotation时报错

```
Resource: "apps.kruise.io/v1alpha1, Resource=sidecarsets", GroupVersionKind: "apps.kruise.io/v1alpha1, Kind=SidecarSet"
Name: "mosn-sidecarset", Namespace: ""
for: "mosn-sidecarset.yaml": admission webhook "vsidecarset.kb.io" denied the request: spec.patchPodMetadata: Required value: SidecarSet patch metadata whitelist not found
```

**What you expected to happen**:

希望能够正常注入annotation用来控制容器启动顺序

**How to reproduce it (as minimally and precisely as possible)**:

**白名单配置yaml**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kruise-configuration
  namespace: kube-system
data:
  "SidecarSet_PatchPodMetadata_WhiteList": |
    {
      "rules": [
        {
          "allowedAnnotationKeyExprs": [
            "^apps.kruise.io/container-launch-priority$"
          ]
        }
      ]
    }
```

**SidecarSet的yaml如下**
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: mosn-sidecarset
  namespace: ***
spec:
  containers:
  - image: ***
    #imagePullPolicy: IfNotPresent
    imagePullPolicy: Always
    name: mosn
    podInjectPolicy: BeforeAppContainer
    resources: {}
    env:
    - name: ENVIRONMENT
      value: uat
    - name: CONSUL_CLIENT_TOKEN
      value: ***
    - name: CONSUL_CLIENT_PORT
      value: '8500'
    - name: CONSUL_CLIENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    shareVolumePolicy:
      type: enabled
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    upgradeStrategy:
      hotUpgradeEmptyImage: openkruise/hotupgrade-sample:empty
      upgradeType: HotUpgrade
    volumeMounts:
    - mountPath: /var/log/mosn
      name: logs
      subPathExpr: mosn
    - mountPath: /var/log/mosn/mem
      name: mosn-mem
    lifecycle:
  patchPodMetadata:
  - annotations:
      apps.kruise.io/container-launch-priority: Ordered
    patchPolicy: Overwrite
  injectionStrategy: {}
  namespace: ptjg-ptjg
  selector:
    matchExpressions:
      - {key: appName, operator: In, values: [***]}
  updateStrategy:
    maxUnavailable: 1
    partition: 0
    type: RollingUpdate
  volumes:
  - hostPath:
      path: /var/log
      type: DirectoryOrCreate
    name: logs
  - emptyDir: {}
    name: mosn-mem
```

**Anything else we need to know?**:
如果需要其他配置请告知
**Environment**:
- Kruise version:1.3.0
- Kubernetes version (use `kubectl version`):v1.19.5
- Install details (e.g. helm install args):
- Others:
