### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kerecsen** [openkruise/kruise#114]
**What happened**:

When I used SidecarSet with Deployment, the sidecar container could be injected to the pod, but the sidecar container could not be updated. There is a quick review(the yaml's detail please see the section 'How to reproduce it'):

after create sidecarset:
```
# kubectl get sidecarsets.apps.kruise.io
NAME                MATCHED   UPDATED   READY   AGE
guestbook-sidecar   0         0         0       35s
```
after creat guestbook-sts-for-sidecar-demo:
```
# kubectl get pod
NAME                                      READY   STATUS    RESTARTS   AGE
guestbook-with-sidecar-7794fc5859-4567d   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-5wx8m   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-6pwv5   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-8qqs9   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-8v8b6   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-bghjf   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-c2jbw   2/2     Running   0          18s
guestbook-with-sidecar-7794fc5859-fpr26   2/2     Running   0          18s
guestbook-with-sidecar-7794fc5859-gjbwj   2/2     Running   0          18s
guestbook-with-sidecar-7794fc5859-hhbpn   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-j6nr6   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-kj7wl   2/2     Running   0          18s
guestbook-with-sidecar-7794fc5859-p6gsv   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-qrcbb   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-r2n44   2/2     Running   0          18s
guestbook-with-sidecar-7794fc5859-rwlgw   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-sn627   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-tjbvx   2/2     Running   0          19s
guestbook-with-sidecar-7794fc5859-vgj54   2/2     Running   0          18s
guestbook-with-sidecar-7794fc5859-zbcdt   2/2     Running   0          19s
```
then see the sidecarsets:
```
# kubectl get sidecarsets.apps.kruise.io
NAME                MATCHED   UPDATED   READY   AGE
guestbook-sidecar   20        20        0       4m23s
```
check the images in pod:
```
# kubectl describe pod guestbook-with-sidecar-7794fc5859-4567d | grep Image:
    Image:          openkruise/guestbook:v1
    Image:          openkruise/guestbook:sidecar
```
you can see the image I run in sidecar is `openkruise/guestbook:sidecar` the same as offical guide. then apply it to openkruise/guestbook:sidecar-v2 and see sidecarsets(no detaction found):

```
# kubectl get sidecarsets.apps.kruise.io
NAME                MATCHED   UPDATED   READY   AGE
guestbook-sidecar   20        0         0       10m
```
check the pod(RESTART not changed):
```
# kubectl get pod
NAME                                      READY   STATUS    RESTARTS   AGE
guestbook-with-sidecar-7794fc5859-4567d   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-5wx8m   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-6pwv5   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-8qqs9   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-8v8b6   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-bghjf   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-c2jbw   2/2     Running   0          8m36s
guestbook-with-sidecar-7794fc5859-fpr26   2/2     Running   0          8m36s
guestbook-with-sidecar-7794fc5859-gjbwj   2/2     Running   0          8m36s
guestbook-with-sidecar-7794fc5859-hhbpn   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-j6nr6   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-kj7wl   2/2     Running   0          8m36s
guestbook-with-sidecar-7794fc5859-p6gsv   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-qrcbb   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-r2n44   2/2     Running   0          8m36s
guestbook-with-sidecar-7794fc5859-rwlgw   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-sn627   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-tjbvx   2/2     Running   0          8m37s
guestbook-with-sidecar-7794fc5859-vgj54   2/2     Running   0          8m36s
guestbook-with-sidecar-7794fc5859-zbcdt   2/2     Running   0          8m37s
```
check the images(no updated):
```
# kubectl describe pod guestbook-with-sidecar-7794fc5859-4567d | grep Image:
    Image:          openkruise/guestbook:v1
    Image:          openkruise/guestbook:sidecar
```

**What you expected to happen**:
```
the sidecar could be updated when SidecarSet is used with Deployment.
```
**How to reproduce it (as minimally and precisely as possible)**:

just follow the offical example "https://github.com/openkruise/kruise/blob/master/docs/tutorial/sidecarset.md" but only change the `guestbook-sts-for-sidecar-demo.yam` to bellow:
```
#apiVersion: apps.kruise.io/v1alpha1
#kind: StatefulSet
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-with-sidecar
  labels:
    app: guestbook
    version: "1.0"
spec:
  replicas: 20
#  serviceName: guestbook-with-sidecar
  selector:
    matchLabels:
      app.kubernetes.io/name:  guestbook-with-sidecar
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  guestbook-with-sidecar
        version: "1.0"
    spec:
      readinessGates:
        # A new condition that ensures the pod remains at NotReady state while the in-place update is happening
        - conditionType: InPlaceUpdateReady
      containers:
      - name: guestbook
        image: openkruise/guestbook:v1
        ports:
        - name: http-server
          containerPort: 3000
#  podManagementPolicy: Parallel  # allow parallel updates, works together with maxUnavailable
#  updateStrategy:
#    type: RollingUpdate
#    rollingUpdate:
#      # Do in-place update if possible, currently only image update is supported for in-place update
#      podUpdatePolicy: InPlaceIfPossible
#      # Allow parallel updates with max number of unavailable instances equals to 2
#      maxUnavailable: 3
```

**Anything else we need to know?**:
1. the SidecarSet works well with StatefulSet(injecting and updating)
2. if we use `apiVersion: apps.kruise.io/v1alpha1` in guestbook-sts-for-sidecar-demo.yaml, there will be an erro when apply it:
```
error: unable to recognize "guestbook-sts-for-sidecar-demo.yaml": no matches for kind "Deployment" in version "apps.kruise.io/v1alpha1"
```
3. Deployment does not support `podManagementPolicy` and `updateStrategy`, so I delete them from the guestbook-sts-for-sidecar-demo.yaml.

**Environment**:
- Kruise version:
```
v0.1.0
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux k8s-company01-master01 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
kubeadm kubectl helm
```
- Others:
