### ISSUE TITLE
[BUG] An error happens when switch an existing StatefulSet resource to Advanced StatefulSet

### ISSUE THREAD

**Issue by andyxning** [openkruise/kruise#1142]
**What happened**:
An error: 
```* : Invalid value: "The edited file failed validation": ValidationError(StatefulSet.status): missing required field "availableReplicas" in io.kruise.apps.v1beta1.StatefulSet.status``` happens when i switch an existing Statefulset Resource to Advanced StatefulSet.

**What you expected to happen**:
It can be changed seamlessly.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: 0.9.0
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
@andyxning How do you operate, can you describe the process in detail and the corresponding yaml file?

**Comment by andyxning** [comment]
I was only update the apiVersion according to the [doc](https://openkruise.io/docs/user-manuals/advancedstatefulset)
```
-  apiVersion: apps/v1
+  apiVersion: apps.kruise.io/v1beta1
   kind: StatefulSet
   metadata:
     name: sample
   spec:
     #...
```
