### ISSUE TITLE
Get unexpected FailedPreStopHook warning when we update advanced stateful set  with in-place update?

### ISSUE THREAD

**Issue by song0071000** [openkruise/kruise#1154]
**What happened**:
Assume the following：

we have statefulset instance whose configure file is demo.yaml. 

demo.yaml [ image: demoImageVersion1, env value from metadata.annotations: demoEnvVersion1, preStop [bash -c sleep 5s]]

Now we update demo.yaml, the filed we change are image, and metadata.annotations. so we can update this service with a in-place way.

After we apply the changed demo yaml, an unexpected warning is reported.

What is puzzling is that kruise-daemon-containermeta report FailedPreStopHook warning which is unexpected.

**What you expected to happen**:

kruise-daemon-containermeta does not report FailedPreStopHook warning

**How to reproduce it (as minimally and precisely as possible)**:

just set a prestop and update advance statefulset instance with image version and envionment variables.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.2.0
- Kubernetes version (use `kubectl version`):1.20.11
- Install details (e.g. helm install args):
- Others:

**Log**:
![image](https://user-images.githubusercontent.com/5143822/210313127-2244bf99-035d-4547-82af-7efca99b4f60.png)

**Comment by zmberg** [comment]
@song0071000 Can you show the whole yaml?

**Comment by veophi** [comment]
@song0071000  Maybe, you cloud try to add `startupProbe` or increase `initialDelaySeconds` for `livenessProbe`.

**Comment by song0071000** [comment]
@zmberg @veophi 

the yaml as follow after desensitization
```
apiVersion: apps.kruise.io/v1beta1
kind: StatefulSet
metadata:
  annotations:
    devops.xx.im/instance-config-version: bison-test-00000000000035c2
  labels:
    devops.xx.im/env: pre
  name: bison-test-pre
  namespace: devops-test-ali-infra4prod
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: bison-test
      devops.xx.im/env: pre
  serviceName: bison-test-pre
  template:
    metadata:
      annotations:
        devops.xx.im/instance-config-version: bison-test-00000000000035c2
      creationTimestamp: null
      labels:
        devops.xx.im/env: pre
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - bison-test
                - key: devops.xx.im/cluster-name
                  operator: In
                  values:
                  - ali-infra4prod
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - bison-test
                - key: devops.xx.im/cluster-name
                  operator: In
                  values:
                  - ali-infra4prod
              topologyKey: kubernetes.io/hostname
            weight: 99
      containers:
      - args:
        - launcher -c && exec ./${APPNAME} -c ${CONFIG_DIR}/app.yaml
        command:
        - bash
        - -c
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: INSTANCE_CONFIG_VERSION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['devops.xx.im/instance-config-version']
        image: xxxx:v1.1.4-73638_17
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -c
              - sleep 5s
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: http-healthy
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: bison-test
        ports:
        - containerPort: 9001
          name: grpc
          protocol: TCP
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 9999
          name: http-healthy
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: http-healthy
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1201
        startupProbe:
          failureThreshold: 24
          httpGet:
            path: /
            port: http-healthy
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/conf
          name: configmap-file
      dnsPolicy: ClusterFirst
      hostIPC: true
      readinessGates:
      - conditionType: InPlaceUpdateReady
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1201
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: configmap-file
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      minReadySeconds: 0
      partition: 0
      podUpdatePolicy: InPlaceIfPossible
    type: RollingUpdate
```


Annotation[devops.xx.im/instance-config-version] and image will be changed in a update job.
