### ISSUE TITLE
[feature request] Support attach metadata in PullImage CRI interface during ImagePulljobs

### ISSUE THREAD

**Issue by furykerry** [openkruise/kruise#1155]
**What would you like to be added**:

When kubelet creates pods, kubelet will attach pod metadata as podSandboxConfig params in the PullImage CRI interface, however if we download image using ImagePulljobs, currently there is no way to attach user metadata into CRI interface, which makes some function infeasible when using ImagePulljobs. 

```
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: job-with-annotations
spec:
  image: nginx:1.9.1  
  # add new fields to specifiy sandbox config
  SandboxConfig:
      annotations:
          io.kubernetes.image.metrics.tags: "app=foo"           
```

**Why is this needed**:
 Image registry can support tag image download traffic with custom label, so that image registry can identify and limit large traffic.
