### ISSUE TITLE
CloneSet scale-down supports topology spread constraints, may lead to topology imbalance duaring deploying.

### ISSUE THREAD

**Issue by zyfcloud** [openkruise/kruise#1162]
**What happened**:
Cloneset scale-down supports topology spread constraints, as mentioned in [652](https://github.com/openkruise/kruise/pull/652), but it only consider the notUpdatedPods,
Duaring the deploying time, it may lead to topology imbalance. 

**What you expected to happen**:
Should consider updated pods's topology spread while scaling down.

**How to reproduce it (as minimally and precisely as possible)**:
（1）cloneset that has 3 pods in 3 logic zone（a、b、c）
（2）change image and set partition 2 at the same time，then it will only rollingupdate one new pod
（3）in my condition，it may lead to topology imbalance like（a:old, b:old, a:new）

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.0.1
- Kubernetes version (use `kubectl version`): v1.22
- Install details (e.g. helm install args): helm install
- Others:

**Comment by zmberg** [comment]
> How to reproduce it (as minimally and precisely as possible):
（1）cloneset that has 3 pods in 3 logic zone（a、b、c）
（2）change image and set partition 1 at the same time，then it will only rollingupdate two new pod
（3）in my condition，it may lead to topology imbalance like（a:new, b:new, a:old）

@zyfcloud I followed this process again, but it didn't reproduce.
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  updateStrategy:
    partition: 1
  template:
    metadata:
      labels:
        app: sample
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: test.zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: sample
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: version
              value: v2
```

```bash
@MacBook-Pro kruise % kubectl get pods -o wide
NAME                READY   STATUS    RESTARTS   AGE     IP             NODE             NOMINATED NODE   READINESS GATES
sample-data-25dc4   1/1     Running   0          63s     10.244.3.197   liheng-worker2   <none>           2/2
sample-data-j7mmw   1/1     Running   0          6m36s   10.244.1.207   liheng-worker    <none>           2/2
sample-data-p547k   1/1     Running   0          17s     10.244.2.172   liheng-worker3   <none>           2/2

@MacBook-Pro kruise % kubectl get clonesets
NAME          DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
sample-data   3         2         2               3       3       10m
```

**Comment by zmberg** [comment]
@zyfcloud Did you adjust the PodSpreadConstraint during the upgrade?

**Comment by zmberg** [comment]
> How to reproduce it (as minimally and precisely as possible):
（1）cloneset that has 3 pods in 3 logic zone（a、b、c）
（2）change image and set partition 2 at the same time，then it will only rollingupdate one new pod
（3）in my condition，it may lead to topology imbalance like（a:new, b:new, a:old）

@zyfcloud According to this step, I did not reproduce the whole process, so can you give more details.

**Comment by zyfcloud** [comment]
> > How to reproduce it (as minimally and precisely as possible):
> > （1）cloneset that has 3 pods in 3 logic zone（a、b、c）
> > （2）change image and set partition 2 at the same time，then it will only rollingupdate one new pod
> > （3）in my condition，it may lead to topology imbalance like（a:new, b:new, a:old）
> 
> @zyfcloud According to this step, I did not reproduce the whole process, so can you give more details. For example, in the second step in your example, only one pod is updated, why there are two new version pods in the third step.

sorry，it's my fault. i have corrected it  in the third step, it may lead to a result like (a:old, b:old, a:new)

**Comment by zyfcloud** [comment]
> @zyfcloud But i did not reproduce the imbalance again, as follows:
> 
> ```yaml
> apiVersion: apps.kruise.io/v1alpha1
> kind: CloneSet
> metadata:
>   labels:
>     app: sample
>   name: sample-data
> spec:
>   replicas: 3
>   selector:
>     matchLabels:
>       app: sample
>   updateStrategy:
>     partition: 2
>   template:
>     metadata:
>       labels:
>         app: sample
>     spec:
>       topologySpreadConstraints:
>         - maxSkew: 1
>           topologyKey: test.zone
>           whenUnsatisfiable: DoNotSchedule
>           labelSelector:
>             matchLabels:
>               app: sample
>       containers:
>         - name: nginx
>           image: nginx:alpine
>           env:
>             - name: version
>               value: v2
> ```
> 
> ```shell
> @MacBook-Pro kruise % kubectl get pods -o wide
> NAME                READY   STATUS    RESTARTS   AGE     IP             NODE             NOMINATED NODE   READINESS GATES
> sample-data-7sj8v   1/1     Running   0          4m22s   10.244.1.214   liheng-worker    <none>           2/2
> sample-data-h5v44   1/1     Running   0          4m21s   10.244.3.206   liheng-worker2   <none>           2/2
> sample-data-wd4cs   1/1     Running   0          3s      10.244.2.184   liheng-worker3   <none>           2/2
> ```

**Comment by zyfcloud** [comment]
1、fisrt step, label node：
```
 kubectl label node txsh-xxxxx-a.1231b694.4 test=test logiczone=a
 kubectl label node txsh-xxxxx-b.rjhua457.0 test=test logiczone=b
 kubectl label node txsh-xxxxx-c.if7rqwqr.0 test=test logiczone=c
```
2、apply the yaml below：
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  updateStrategy:
    maxSurge: 75%
    maxUnavailable: 0
    partition: 0
    type: ReCreate
  template:
    metadata:
      labels:
        app: sample
        workload: cloneset
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: test
                    operator: In
                    values:
                      - test
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: sample
              workload: cloneset
          maxSkew: 1
          topologyKey: logiczone
          whenUnsatisfiable: DoNotSchedule
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: version
              value: v1
```

```
kubectl get pods -n base -l app=sample -owide
NAME                READY   STATUS    RESTARTS   AGE   IP               NODE                              NOMINATED NODE   READINESS GATES
sample-data-cx87g   1/1     Running   0          8s    172.30.39.193    xxxxx-b.1231b694.0   <none>           3/3
sample-data-k4jzp   1/1     Running   0          8s    172.30.226.113   xxxxx-a.rjhua457.4   <none>           3/3
sample-data-sdt6p   1/1     Running   0          8s    172.30.43.155    xxxxx-c.if7rqwqr.0   <none>           3/3
```

3、change the version and partition as below：
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  updateStrategy:
    maxSurge: 75%
    maxUnavailable: 0
    partition: 2
    type: ReCreate
  template:
    metadata:
      labels:
        app: sample
        workload: cloneset
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: test
                    operator: In
                    values:
                      - test
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: sample
              workload: cloneset
          maxSkew: 1
          topologyKey: logiczone
          whenUnsatisfiable: DoNotSchedule
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: version
              value: v2
```
4、watch pods：
```
kubectl get pods -n base -l app=sample -owide -w
NAME                READY   STATUS    RESTARTS   AGE   IP               NODE                              NOMINATED NODE   READINESS GATES
sample-data-cx87g   1/1     Running   0          11s   172.30.39.193    xxxxx-b.1231b694.0   <none>           3/3
sample-data-k4jzp   1/1     Running   0          11s   172.30.226.113   xxxxx-a.rjhua457.4   <none>           3/3
sample-data-sdt6p   1/1     Running   0          11s   172.30.43.155    xxxxx-c.if7rqwqr.0   <none>           3/3
sample-data-b8rm5   0/1     Pending   0          0s    <none>           <none>                            <none>           0/3
sample-data-b8rm5   0/1     ContainerCreating   0          0s    <none>           xxxxx-b.1231b694.0   <none>           3/3
sample-data-b8rm5   1/1     Running             0          5s    172.30.39.194    xxxxx-b.1231b694.0   <none>           3/3
sample-data-k4jzp   1/1     Terminating         0          21s   172.30.226.113   xxxxx-a.rjhua457.4   <none>           3/3
sample-data-b8rm5   1/1     Running             0          6s    172.30.39.194    xxxxx-b.1231b694.0   <none>           3/3
```
As we can see, it created a new pod in logic b, but killed an old in logic a. 
As a result, it will has two pods in logic b, but 0 pods in logic a.

**Comment by zmberg** [comment]
@zyfcloud You are right, i already reproducer you issue.

**Comment by zmberg** [comment]
@zyfcloud You are right, but this issue is difficult to solve, for examples:
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
spec:
  replicas: 3
  updateStrategy:
    maxSurge: 75%
    maxUnavailable: 0
    partition: 2
    type: ReCreate
```
1. a(pod-v2), b(pod-v1), c(pod-v1)
2. set partition = 0, and because maxSurge=75%, then first create two new pods, and don't delete any pod.
3. a(pod-v2, pod-v2), b(pod-v1, pod-v2), c(pod-v1)
4. finally, delete all old version pods
5. a(pod-v2, pod-v2), b(pod-v2)
Similarly, I have verified similar configurations in deployment, and the same problem will exist. Are you have good idea for this?
