### ISSUE TITLE
Container failed due to cgroup cannot write file

### ISSUE THREAD

**Issue by horacexd** [openkruise/kruise#1180]
**What happened**:
I create a pod under advanced statefulset (asts) with inplace update for image enable.  
And I used in-place update feature on CPU/Mem from upstream. 
https://github.com/kubernetes/kubernetes/pull/102884/
When I edit nginx-asts and change image from nginx:1.14.2 to nginx:1.14.1 and CPU from 1 to 2 both in limits and requests, the pod will get into the CrashLoopBackoff. Checked the pod error message:

```yaml
'failed to create containerd task: OCI runtime create failed: container_linux.go:370:
          starting container process caused: process_linux.go:459: container init
          caused: process_linux.go:422: setting cgroup config for procHooks process
          caused: failed to write "200000" to "/sys/fs/cgroup/cpu,cpuacct/kubepods/podc366e2e3-155e-4d4b-a36d-369042e75266/1d33192617684dc3ddccc42d4d370c0e8a3b27bb19630a3c29037d52093a5935/cpu.cfs_quota_us":
          write /sys/fs/cgroup/cpu,cpuacct/kubepods/podc366e2e3-155e-4d4b-a36d-369042e75266/1d33192617684dc3ddccc42d4d370c0e8a3b27bb19630a3c29037d52093a5935/cpu.cfs_quota_us:
          invalid argument: unknown'
```
**What you expected to happen**:
Since pod enable Open Kruise inplace update on image, pod will have RESTART counter +1
Since kubelet is used inplace update for CPU/Mem, container status will have 
```yaml
resourcesAllocated:
      cpu: "2"
```
**How to reproduce it (as minimally and precisely as possible)**:
Build kubelet with https://github.com/kubernetes/kubernetes/pull/102884/
Deploy Openkruise
Apply asts.yaml
```yaml
apiVersion: apps.kruise.io/v1beta1
kind: StatefulSet
metadata:
  creationTimestamp: "2023-02-13T19:12:44Z"
  generation: 5
  labels:
    app: nginx
  name: nginx-asts
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      readinessGates:
      - conditionType: InPlaceUpdateReady
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      minReadySeconds: 0
      partition: 0
      podUpdatePolicy: InPlaceIfPossible
    type: RollingUpdate
```
Wait for the pod is in running stage
Edit asts and:
1. change spec/template/spec/containers/0/image from nginx:1.14.2 to nginx:1.14.1
2. change spec/template/spec/containers/0/resources/requests/cpu from 1 to 2 
3. change spec/template/spec/containers/0/resources/limits/cpu from 1 to 2
Save asts and exit 

**Anything else we need to know?**:
None

**Environment**:
- Kruise version: release-1.0
- Kubernetes version (use `kubectl version`):
```bash
  Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.16-vke.1", GitCommit:"9be13fe754df90aadcf00811ad071ea36ea29116", GitTreeState:"clean", BuildDate:"2022-09-07T15:42:42Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.3.511+4017d508885e65-dirty", GitCommit:"4017d508885e65a298fbc2f5091765faf1c838cb", GitTreeState:"dirty", BuildDate:"2022-04-06T16:39:56Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Install details (e.g. helm install args): None
- Others: None
