### ISSUE TITLE
[BUG] WorkloadSpread 拓扑分布更新时候未按照预期工作

### ISSUE THREAD

**Issue by a33151** [openkruise/kruise#1194]
**What happened**:
WorkloadSpread 拓扑分布在更新的时候不生效

我期望是:
common标签是2个pod
spot标签是8个pod

如何复现:

我的WorkloadSpread如下:

```

apiVersion: apps.kruise.io/v1alpha1
kind: WorkloadSpread
metadata:
  name: test-project-zjj-test-co225-121321-cp
  namespace: test-product
spec:
  subsets:
  - maxReplicas: 2
    name: common
    patch:
      metadata:
        labels:
          biz.type: common
    requiredNodeSelectorTerm:
      matchExpressions:
      - key: biz.type
        operator: In
        values:
        - common
  - maxReplicas: 8
    name: spot
    patch:
      metadata:
        labels:
          biz.type: spot
    requiredNodeSelectorTerm:
      matchExpressions:
      - key: biz.type
        operator: In
        values:
        - spot
  targetRef:
    apiVersion: apps.kruise.io/v1alpha1
    kind: CloneSet
    name: test-project-zjj-test-co225-121321-cp
```

我部署了 replica 为10 的部署.
第一次apply 我的测试部署时候, 拓扑分布是正常的

```
root@k8s-master-670ba4fbb4:~/test# kubectl get po -n  test-product -l  biz.type=spot
NAME                                          READY   STATUS    RESTARTS   AGE
test-project-zjj-test-co225-121321-cp-7nnqd   1/1     Running   0          33s
test-project-zjj-test-co225-121321-cp-fkvql   1/1     Running   0          32s
test-project-zjj-test-co225-121321-cp-mw6zb   1/1     Running   0          32s
test-project-zjj-test-co225-121321-cp-s642l   1/1     Running   0          32s
test-project-zjj-test-co225-121321-cp-slc8g   1/1     Running   0          32s
test-project-zjj-test-co225-121321-cp-tmszn   1/1     Running   0          32s
test-project-zjj-test-co225-121321-cp-w8tzm   1/1     Running   0          32s
test-project-zjj-test-co225-121321-cp-zgspv   1/1     Running   0          32s
root@k8s-master-670ba4fbb4:~/test# kubectl get po -n  test-product -l  biz.type=common
NAME                                          READY   STATUS    RESTARTS   AGE
test-project-zjj-test-co225-121321-cp-74r25   1/1     Running   0          36s
test-project-zjj-test-co225-121321-cp-cjpq4   1/1     Running   0          36s
```

我编辑我的yaml,修改cpu limit

再次apply, 其中有一个pod没有被标记任何的biz.type标签,并且common上只有1个pod
```
root@k8s-master-670ba4fbb4:~/test# kubectl get po -n  test-product -l  biz.type=common
NAME                                          READY   STATUS    RESTARTS   AGE
test-project-zjj-test-co225-121321-cp-2kxjh   1/1     Running   0          79s

root@k8s-master-670ba4fbb4:~/test# kubectl get po -n  test-product -l  biz.type=spot
NAME                                          READY   STATUS    RESTARTS   AGE
test-project-zjj-test-co225-121321-cp-2s2dq   1/1     Running   0          84s
test-project-zjj-test-co225-121321-cp-9pwnq   1/1     Running   0          96s
test-project-zjj-test-co225-121321-cp-bb2cr   1/1     Running   0          83s
test-project-zjj-test-co225-121321-cp-n8prs   1/1     Running   0          83s
test-project-zjj-test-co225-121321-cp-nmskh   1/1     Running   0          96s
test-project-zjj-test-co225-121321-cp-s2j95   1/1     Running   0          69s
test-project-zjj-test-co225-121321-cp-t9wxn   1/1     Running   0          97s
test-project-zjj-test-co225-121321-cp-v6lnd   1/1     Running   0          97s

root@k8s-master-670ba4fbb4:~/test# kubectl get po -n test-product
NAME                                          READY   STATUS    RESTARTS   AGE
test-project-zjj-test-co225-121321-cp-2kxjh   1/1     Running   0          91s
test-project-zjj-test-co225-121321-cp-2s2dq   1/1     Running   0          92s
test-project-zjj-test-co225-121321-cp-9pwnq   1/1     Running   0          104s
test-project-zjj-test-co225-121321-cp-bb2cr   1/1     Running   0          91s
test-project-zjj-test-co225-121321-cp-n8prs   1/1     Running   0          91s
test-project-zjj-test-co225-121321-cp-nmskh   1/1     Running   0          104s
test-project-zjj-test-co225-121321-cp-s2j95   1/1     Running   0          77s
test-project-zjj-test-co225-121321-cp-t9wxn   1/1     Running   0          105s
test-project-zjj-test-co225-121321-cp-v6lnd   1/1     Running   0          105s
test-project-zjj-test-co225-121321-cp-zkr7t   1/1     Running   0          105s
```

**Environment**:
- Kruise version:
- 1.3
- Kubernetes version (use `kubectl version`):
- 1.20.10

请问是我这边配置的问题吗?
