### ISSUE TITLE
[BUG] No default patch strategy for cloneset spec

### ISSUE THREAD

**Issue by Shubhamurkade** [openkruise/kruise#1195]
**What happened**:
Trying to patch cloneset to change the scaleStrategy with the following yaml:

```spec:
  replicas: 4
  scaleStrategy:
    podsToDelete:
    - sample-gmkfj
```

Throws the following error: _error: must specify --patch or --patch-file containing the contents of the patch_

Patch command used: `kubectl patch cloneset sample <patch-file>`

Using `--type merge` with the above command works fine.

Cloneset was created with the following yaml:

```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
```
**What you expected to happen**: There should be a default patch policy such that without specifying patch type in `kubectl patch` command, the patch should be applied

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
