### ISSUE TITLE
[feature request] Add ImageListPullJob to simplify ImagePullJob

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1211]
**What would you like to be added**:
Current ImagePullJob can pre-download image to node, for example:
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: job-with-always
spec:
  image: nginx:1.9.1   # [required] image to pull
  selector:            # [optional] the names or label selector to assign Nodes (only one of them can be set)
    names:
    - node-1
    - node-2
    matchLabels:
      node-type: xxx
```
However, many users have the need for batch pre-download images, and the current approach has a relatively high threshold for use, So I think to add a new CRD ImageListPullJob to batch pre-download images, for example:
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: ImageListPullJob
metadata:
  name: job-with-always
spec:
  images: 
  - nginx:1.9.1 
  - busybox:1.19.1
  - httpd:2.4.38
  - ...
  selector: 
    names:
    - node-1
    - node-2
    matchLabels:
      node-type: xxx
```

We can add new controller for CRD ImageListPullJob, and the controller generate some ImagePullJobs to complete the pre-download task.
