### ISSUE TITLE
[BUG] initContainer BeforeAppContainer not effective

### ISSUE THREAD

**Issue by 13567436138** [openkruise/kruise#1215]
**What happened**:
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  initContainers:
  - name: sidecar1
    image: busybox
    command: ["sleep", "1"]
    podInjectPolicy: BeforeAppContainer
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes:
  - name: log-volume
    emptyDir: {}
```
the result is:
```
 containers:
  - image: nginx:alpine
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-x2n6d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sleep
    - "1"
    env:
    - name: IS_INJECTED
      value: "true"
    image: busybox
    imagePullPolicy: Always
    name: sidecar1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: log-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-x2n6d
      readOnly: true小平
```

initContainers is after containers

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:1.3.0
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
