### ISSUE TITLE
[BUG] initContainers shareVolumePolicy is not effective

### ISSUE THREAD

**Issue by 13567436138** [openkruise/kruise#1216]
**What happened**:
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  initContainers:
  - name: sidecar1
    image: busybox
    command: ["sleep", "1"]
    shareVolumePolicy:
      type: enabled
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes:
  - name: log-volume
    emptyDir: {}
```

the result is :
```
spec:
  containers:
  - image: nginx:alpine
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /test
      name: test
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sttkv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sleep
    - "1"
    env:
    - name: IS_INJECTED
      value: "true"
    image: busybox
    imagePullPolicy: Always
    name: sidecar1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: log-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sttkv
      readOnly: true
```

no volume shared

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:1.3.0
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
