### ISSUE TITLE
[BUG] unitedDeployment调度不对

### ISSUE THREAD

**Issue by 13567436138** [openkruise/kruise#1230]
**What happened**:
unitedDeployment/ud-topology-subsets-nodeSelectorTerm-matchFields.yaml

```
apiVersion: apps.kruise.io/v1alpha1
kind: UnitedDeployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    deploymentTemplate:
      metadata:
        labels:
          app: nginx
      spec:
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - image: nginx:alpine
              name: nginx
  topology:
    subsets:
    - name: subset-a
      nodeSelectorTerm:
        matchFields:
          - key: metadata.name
            operator: In
            values:
            - 192.168.229.128
      replicas: 2
    - name: subset-b
      nodeSelectorTerm:
        matchFields:
          - key: metadata.name
            operator: In
            values:
            - 192.168.229.129
      replicas: 50%
```

```
kubectl apply -f ud-topology-subsets-nodeSelectorTerm-matchFields.yaml -n kruise
 
 
[root@node01 ~]# kubectl get deploy -n kruise
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
nfs-client-provisioner   0/1     1            0           107d
nginx-subset-a-xd8rp     2/2     2            2           5s
nginx-subset-b-8zkqf     3/3     3            3           5s

[root@node01 ~]# kubectl get pod -n kruise -w -owide
NAME                                      READY   STATUS              RESTARTS   AGE     IP             NODE              NOMINATED NODE   READINESS GATES
nfs-client-provisioner-69557bfdb8-4ld7w   0/1     ContainerCreating   0          132m    <none>         192.168.229.129   <none>           <none>
nginx-subset-a-xd8rp-7ccd74c65b-drxsw     1/1     Running             0          3m24s   172.20.0.189   192.168.229.128   <none>           <none>
nginx-subset-a-xd8rp-7ccd74c65b-nkz5v     1/1     Running             0          3m24s   172.20.0.190   192.168.229.128   <none>           <none>
nginx-subset-b-8zkqf-5c4cfcf897-c9v7g     1/1     Running             0          3m24s   172.20.0.191   192.168.229.128   <none>           <none>
nginx-subset-b-8zkqf-5c4cfcf897-jlwsl     1/1     Running             0          3m24s   172.20.2.53    192.168.229.130   <none>           <none>
nginx-subset-b-8zkqf-5c4cfcf897-k45dt     1/1     Running             0          3m24s   172.20.0.192   192.168.229.128   <none>           <none>
```
```
[root@node01 ~]# kubectl get node
NAME              STATUS   ROLES    AGE    VERSION
192.168.229.128   Ready    master   560d   v1.21.0
192.168.229.129   Ready    master   560d   v1.21.0
192.168.229.130   Ready    node     560d   v1.21.0
```
192.168.229.129应该有3个，128应该是两个，不对
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
