### ISSUE TITLE
[feature request] 修改镜像和env （from label），openKruise原地升级容器会重启两次，希望可以优化成重启一次

### ISSUE THREAD

**Issue by a932846905** [openkruise/kruise#1239]
**在原地升级时，同时修改镜像以及env（from label），发现容器会重启两次。根据Pod Event，一次是kubelet kill，一次是kruise-daemon-containermeta kill   希望可以优化成只重启成一次。**:
![image](https://user-images.githubusercontent.com/30947364/228217968-80128660-9379-4b3c-b412-6e0eedd2074c.png)

**优化用户体验，降低告警，服务注册等其他依赖容器状态检测的组件复杂度。**:

**Comment by zmberg** [comment]
我测试了一下，发现只会重启一次，配置如下：
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 1
  updateStrategy:
    type: InPlaceIfPossible
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
        test: liheng1
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          env:
          - name: MY_POD_LABEL_APP
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['test']
```
我同时修改了 image 和 labels[test] 发现只会重启一次，并且 labels[test] 生效了
```
Events:
  Type    Reason          Age                  From               Message
  ----    ------          ----                 ----               -------
  Normal  Scheduled       2m33s                default-scheduler  Successfully assigned default/sample-5tdmw to cn-beijing.192.168.55.125
  Normal  AllocIPSucceed  2m33s                terway-daemon      Alloc IP 192.168.55.174/18
  Normal  Pulling         2m33s                kubelet            Pulling image "nginx:stable-alpine3.17"
  Normal  Pulled          2m31s                kubelet            Successfully pulled image "nginx:stable-alpine3.17" in 1.702488262s (1.702495688s including waiting)
  Normal  Killing         42s                  kubelet            Container nginx definition changed, will be restarted
  Normal  Pulling         42s                  kubelet            Pulling image "nginx:stable-alpine"
  Normal  Created         40s (x2 over 2m31s)  kubelet            Created container nginx
  Normal  Started         40s (x2 over 2m31s)  kubelet            Started container nginx
  Normal  Pulled          40s                  kubelet            Successfully pulled image "nginx:stable-alpine" in 1.710641595s (1.710650682s including waiting)
```
