### ISSUE TITLE
[BUG] SidecarSet works in some namespaces and not in others

### ISSUE THREAD

**Issue by ktalg** [openkruise/kruise#1264]
**What happened**:
I tried using SidecarSet resource in my Kubernetes cluster, but it didn't work as expected. The specified sidecar container was not injected into my declared pod.

**What you expected to happen**:
I expected the SidecarSet resource to inject the specified container into my declared pod.

**How to reproduce it (as minimally and precisely as possible)**:
1. Declare a SidecarSet resource with a container specification,and wait for seconds.
2. Declare a pod with appropriate specifications.
3. Observe that the container specified in the SidecarSet is not injected into the declared pod,there's only one container
```yaml
containers:
- image: nginx:1.15.1
imagePullPolicy: IfNotPresent
name: app
resources: {}
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
volumeMounts:
- mountPath: /var/run/secrets/kubernetes.io/serviceaccount
name: kube-api-access-rxxq7
readOnly: true
```

**Anything else we need to know?**:
pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx # matches the SidecarSet's selector
  name: test-pod
  namespace: ns
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
    - name: app
      image: nginx:1.15.
```

sidecarset:(just from official website,no namespace-based selector declared）
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  containers:
    - name: sidecar1
      image: centos:6.7
      command: ["sleep", "999d"] # do nothing at all
      volumeMounts:
        - name: log-volume
          mountPath: /var/log
  volumes: # this field will be merged into pod.spec.volumes
    - name: log-volume
      emptyDir: {}
```

It's very strange that sidecar can be injected normally when that pod is declared in **another namespace**, and I'm pretty sure I'm not using a [namespace selector](https://openkruise.io/zh/docs/user-manuals/sidecarset/#namespace-selector) 

Also, I did not change the webhook declaration, it is the default configuration
```yaml
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        
<SOMETHING UNIMPORTANT>
      service:
        name: kruise-webhook-service
        namespace: kruise-system
        path: /mutate-pod
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: mpod.kb.io
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 30
```

I noticed that when the injection is successful, kruise prints some logs container `sidecar inject...`, while when creating a pod with an unsuccessful injection, nothing is generated

**Environment**:
- Kruise version: image:kruise-manager:v1.2.0
- Kubernetes version (use `kubectl version`):1.22.3
- Install details (e.g. helm install args):
- Others:

**Comment by furykerry** [comment]
pls check whether the namespace labels that failed to get sidecar injected, one possible reason is that the namespace contains the control-plane label

**Comment by ktalg** [comment]
> pls check whether the namespace labels that failed to get sidecar injected, one possible reason is that the namespace contains the control-plane label

Oh, looks like I missed this
```
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
```
I found that namespaces that failed to get sidecar injection do have the tag `control-plane: controller-manager` on them and it works after removing that.

By the way, just out of curiosity, is "exclude control-plane namespaces for sidecar injection" some kind of default paradigm? This information doesn't seem to appear in the [documentation](https://openkruise.io/zh/docs/user-manuals/sidecarset)
