### ISSUE TITLE
[BUG] Image Pre-download failed in k8s 1.26

### ISSUE THREAD

**Issue by sleepyyj** [openkruise/kruise#1273]
**What happened**:
One image Pre-download failed while others went well with k8s version 1.26. But all images went well with k8s 1.23.

**What you expected to happen**:
Expect all images to download successfully with k8s 1.26.

**How to reproduce it (as minimally and precisely as possible)**:
Create an ImagePullJob below:
```
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: astar-wasm-job
  namespace: kruise-system
spec:
  completionPolicy:
    type: Never
  image: whitematrixlab/astar-wasm:astar-wasm-v0.0.2
  pullPolicy:
    backoffLimit: 3
    timeoutSeconds: 300
```
then we'll see the job fail in 1 minute.

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.4.0
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.2-eks-a59e1f0", GitCommit:"8b68f4b95d7121d039ceebd30870e48acc7772e4", GitTreeState:"clean", BuildDate:"2023-03-09T19:59:45Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
- Install details (e.g. helm install args): 
- Others:
