### ISSUE TITLE
Add updatedAvailableReplicas field to CloneSet and Advanced StatefulSet

### ISSUE THREAD

**Issue by veophi** [openkruise/kruise#1305]
**What would you like to be added**:
For example:
```yaml
status:
  updatedReplicas: 10
  updatedReadyReplicas: 10
  updatedAvailableReplicas: 9
```

**Why is this needed**:
People who is rolling his CloneSet/StatefulSet in batches may need this field to judge whether current batch is available.
