### ISSUE TITLE
[BUG] SidecarSet update doesn't work

### ISSUE THREAD

**Issue by MarkLux** [openkruise/kruise#1307]
**What happened**:

I have 3 pods with label `app=demo-server`, then I create a SidecarSet with this label, and sidecar containers injected successfully.

change the sidecar yaml to update the image and apply, but no one of exist pods update or restart, still using the old image.

the sidecar resource is defined as below (the image has been changed from 'busybox' to 'nginx')

```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: demo-sidecarset
spec:
  selector:
    matchLabels:
      app: demo-server
  updateStrategy:
    type: RollingUpdate
    partition: 2
    maxUnavailable: 3
  containers:
  - name: sidecar
    image: nginx # used to be 'busybox'
```

the pods are created by a CloneSet:

```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: demo-server
  name: demo-server
spec:
  updateStrategy:
    type: InPlaceIfPossible
  replicas: 3
  selector:
    matchLabels:
      app: demo-server
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
      - name: demo-server
        image: registry.cn-qingdao.aliyuncs.com/marklux/demo-server:1.2
        ports:
        - containerPort: 8080
```

**What you expected to happen**:

the pods with label `app=demo-server` should be updated, and change the sidecar container's image

**How to reproduce it (as minimally and precisely as possible)**:

1. create a cloneset
2. create a sidecarset
3. delete all the cloneset's pod (in order to inject the sidecar), then we got 3 new pods with sidecar injected
4. change the sidecarset definition and apply

**Anything else we need to know?**:

`kubectl describe sidecarset demo-sidecarset`:

```
Name:         demo-sidecarset
Namespace:
Labels:       <none>
Annotations:  kruise.io/sidecarset-hash: fx9bx26f62b258c6bzdv479zzc782zz7cdwvfb9zcx5dvdcw59cww78zd79xwzw6
              kruise.io/sidecarset-hash-without-image: 2c67wcd97zb88wbwfbzddv4cc56vz5fww9bzcx7464wx65d497f24v42v5f289bw
API Version:  apps.kruise.io/v1alpha1
Kind:         SidecarSet
Metadata:
  Creation Timestamp:  2023-06-05T08:20:50Z
  Generation:          3
  Resource Version:    1655513
  UID:                 a2c0a74c-5c12-44e6-88bd-75e1a0a33f9e
Spec:
  Containers:
    Image:              nginx
    Image Pull Policy:  Always
    Name:               sidecar
    Pod Inject Policy:  BeforeAppContainer
    Resources:
    Share Volume Policy:
      Type:                      disabled
    Termination Message Path:    /dev/termination-log
    Termination Message Policy:  File
    Upgrade Strategy:
      Upgrade Type:  ColdUpgrade
  Injection Strategy:
  Revision History Limit:  10
  Selector:
    Match Labels:
      App:  demo-server
  Update Strategy:
    Max Unavailable:  3
    Partition:        2
    Type:             RollingUpdate
Status:
  Collision Count:      0
  Latest Revision:      demo-sidecarset-687d9df675
  Matched Pods:         3
  Observed Generation:  3
  Ready Pods:           3
  Updated Pods:         0
```

**Environment**:
- Kruise version: 1.4.0
- Kubernetes version (use `kubectl version`): v1.23
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
@MarkLux You can see this issue https://github.com/openkruise/kruise/issues/1272, I think it is the same question.

**Comment by MarkLux** [comment]
> @MarkLux You can see this issue #1272, I think it is the same question.

@zmberg thanks for your reply, But in my case I only changed the image field of sidecar set (and the UpdateStrategy), and the kruise-daemon works normally. 

```
NAME                                         READY   STATUS    RESTARTS   AGE
kruise-controller-manager-75d65fcf87-bkq4s   1/1     Running   0          11d
kruise-controller-manager-75d65fcf87-l6vtc   1/1     Running   0          11d
kruise-daemon-h5rf9                          1/1     Running   0          11d
```

I think my problem is different from that one.

However, if there is any way to check why the pod not change? I checked my pod events and not found any info about my action of updating sidecarset:

```
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  29m   default-scheduler  Successfully assigned default/demo-server-424lg to minikube
  Normal  Pulling    29m   kubelet            Pulling image "busybox"
  Normal  Pulled     29m   kubelet            Successfully pulled image "busybox" in 3.871071959s
  Normal  Created    29m   kubelet            Created container sidecar
  Normal  Started    29m   kubelet            Started container sidecar
  Normal  Pulling    29m   kubelet            Pulling image "registry.cn-qingdao.aliyuncs.com/marklux/demo-server:1.2"
  Normal  Pulled     29m   kubelet            Successfully pulled image "registry.cn-qingdao.aliyuncs.com/marklux/demo-server:1.2" in 394.384875ms
  Normal  Created    29m   kubelet            Created container demo-server
  Normal  Started    29m   kubelet            Started container demo-server
---> I updated the sidecarset and there is no event about the upgrade
```

**Comment by zmberg** [comment]
@MarkLux You can compare annotations[kruise.io/sidecarset-hash-without-image] between Pod and SidecarSet. The value should be equal.

**Comment by MarkLux** [comment]
> @MarkLux You can compare annotations[kruise.io/sidecarset-hash-without-image] between Pod and SidecarSet. The value should be equal.

@zmberg You are right, the annotation `kruise.io/sidecarset-hash-without-image` is not same between my sidecarset and pod, I rechecked my actions and found that I  also changed the  `command` field when I modify the sidecarset:

the SidecarSet definition before:
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: demo-sidecarset
spec:
  selector:
    matchLabels:
      app: demo-server
  updateStrategy:
    type: RollingUpdate
    partition: 2
    maxUnavailable: 3
  containers:
  - name: sidecar
    image: busybox
    command: [ "/bin/sh", "-c", "touch a.txt && tail -f a.txt"]
```

the SidecarSet definition after:

```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: demo-sidecarset
spec:
  selector:
    matchLabels:
      app: demo-server
  updateStrategy:
    type: RollingUpdate
    partition: 2
    maxUnavailable: 3
  containers:
  - name: sidecar
    image: nginx
```

I removed the `command` field, that's the reason.

btw, it would be better if we can add an information into sidecarset's event or log for this problem (maybe I can give a try)
