### ISSUE TITLE
[feature request] SidecarSet updateStrategy support priorityStrategy

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1313]
**What would you like to be added**:
CloneSet updateStrategy support [priorityStrategy](https://openkruise.io/docs/user-manuals/cloneset#priority), SidecarSet also need to support this feature:
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
spec:
  # ...
  updateStrategy:
    priorityStrategy:
      weightPriority:
      - weight: 50
        matchSelector:
          matchLabels:
            test-key: foo
      - weight: 30
        matchSelector:
          matchLabels:
            test-key: bar
```
