### ISSUE TITLE
[BUG] 在程序中将 CloneSet Pod Annotation 的配置设置为 nil 导致 kruise-manager panic

### ISSUE THREAD

**Issue by Fize** [openkruise/kruise#1326]
**What happened**:
在程序中修改 CloneSet 的配置，将其中的 Annotation 设置为 nil 会导致 kruise-manager panic

![image](https://github.com/openkruise/kruise/assets/17003518/1a1014ae-6d2d-436e-9ae2-092727e668e6)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

测试 cloneset 配置：
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-crush
  template:
    metadata:
      annotations:
        app: test
      labels:
        app: test-crush
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
      restartPolicy: Always
  updateStrategy:
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 30
    maxSurge: "0"
    maxUnavailable: 20%
    partition: 0
    type: InPlaceOnly
```

使用的测试程序：

```go
package main

import (
	"context"
	"flag"
	"fmt"
	"path/filepath"

	kruiseclientset "github.com/openkruise/kruise-api/client/clientset/versioned"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/util/homedir"
)

var (
        namespace = "default"
        name = "test"
)

func main() {
	var kubeconfig *string
	if home := homedir.HomeDir(); home != "" {
		kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
	} else {
		kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
	}
	flag.Parse()
	cfg, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
	if err != nil {
		panic(err.Error())
	}
	kruiseClient := kruiseclientset.NewForConfigOrDie(cfg)
	cloneSet, err := kruiseClient.AppsV1alpha1().CloneSets(namespace).Get(context.Background(), name, metav1.GetOptions{})
	if err != nil {
		panic(err)
	}
	cloneSet.Spec.Template.Annotations = nil
	_, err = kruiseClient.AppsV1alpha1().CloneSets(namespace).Update(context.Background(), cloneSet, metav1.UpdateOptions{})
	if err != nil {
		panic(err)
	}
}
```

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.4.0
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
