### ISSUE TITLE
[vsidecarset.kb.io] 部署filebeat-sidecarset.yml找不到卷

### ISSUE THREAD

**Issue by wolf27w** [openkruise/kruise#1328]
我的环境，原本使用的是阿里云托管的ack，1.22.15版本的，安装什么的都没问题，执行也没问题，收集日志正常，然后在自建的1.23.2版本的时候，执行filebeat-sidecarset.yml异常。下面是我的文件内容：
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: filebeat-sidecarset
spec:
  selector:
    # 需要注入 sidecar 容器的 pod labels
    matchLabels:
      kruise.io/inject-filebeat: "true"
  #namespace: default
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  containers:
  - args:
    - -e
    - -E
    - http.enabled=true
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MODULE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['app']
    image: elastic/filebeat:8.6.2
    name: filebeat
    resources:
      limits:
        cpu: "1"
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    podInjectPolicy: AfterAppContainer
    volumeMounts:
    - mountPath: /usr/share/filebeat/filebeat.yml
      readOnly: true
      subPath: filebeat.yml
      name: filebeat-config
    - mountPath: /var/log
      name: log
    podInjectPolicy: AfterAppContainer
  volumes:
  - configMap:
      name: filebeat-config
    name: filebeat-config
  - name: log
    emptyDir: {}
  - name: host-time
    hostPath:
      path: /etc/localtime
```

报错信息：
Error from server: error when creating "filebeat-sidecarset.yml": admission webhook "vsidecarset.kb.io" denied the request: [spec.volumes[0].name: Required value, spec.volumes[1].name: Required value, spec.volumes[2].name: Required value, spec.containers[0].volumeMounts[0].name: Not found: "filebeat-config", spec.containers[0].volumeMounts[1].name: Not found: "log"]
