### ISSUE TITLE
Sidecarset suppot statefulset/deployment etc workload.

### ISSUE THREAD

**Issue by mikechengwei** [openkruise/kruise#133]
**What would you like to be added**:
Sidecarset support statefulset/deployment etc workload.

**Why is this needed**:
I use sidecarset to inject log container into pod,i deployed with my custom resources like sts.
Then i find the inject container not inherit my serviceAccount volumesMount, which used to communicate with k8s api .So I think the sidecarset need to support higher workload level .Becasuse we rarely deploy pod alone.

**Comment by Fei-Guo** [comment]
@mikechengwei 
The feature you request does not exist in Kruise v0.1.0. The good news is that we implemented adding volume support in SidecarSet which is part of v0.2.0 release. Now if you add service account volume and volume mount in SidecarSet using the same service secret name, For example:
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: guestbook-sidecar
spec:
  selector: # select the pods to be injected with sidecar containers
    matchLabels:
      app.kubernetes.io/name: guestbook-with-sidecar
  containers:
    - name: guestbook-sidecar
      image: openkruise/guestbook:sidecar
      imagePullPolicy: Always
      ports:
        - name: sidecar-server
          containerPort: 4000 # different from main guestbook containerPort which is 3000
      volumeMounts:
        - mountPath: /tmp/cert
          name: sidecar-service-account
          readOnly: true
  volumes:
    - name: sidecar-service-account
      secret:
        defaultMode: 420
        secretName: default-token-XXXXX
```
The created sidecar container can access the service token. For example:
```
Containers:
  guestbook:
    Container ID:   docker://2d58010fc025c86129c649600506ef77d2faf80b1725c019141f880c54fe142c
    Image:          openkruise/guestbook:v1
    Image ID:       docker-pullable://openkruise/guestbook@sha256:a5b6e5462982ca795fa9c7ddc378ea5b24a31e5d57eb806095526f7b21384dbd
    Port:           3000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 23 Sep 2019 14:11:18 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-XXXXX(ro)
  guestbook-sidecar:
    Container ID:   docker://4eb44c335af0fe79cc879bc3051e30917a32ff999c1c39283cb1bb4dd93f2176
    Image:          openkruise/guestbook:sidecar
    Image ID:       docker-pullable://openkruise/guestbook@sha256:016eddf673cc7afc5da2fa96b5148161b521cff20583fb1d0c3aa44e6ac75272
    Port:           4000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 23 Sep 2019 14:11:20 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      IS_INJECTED:  true
    Mounts:
      /tmp/cert from sidecar-service-account (ro)

Volumes:
  default-token-XXXXX:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-XXXXX
    Optional:    false
  sidecar-service-account:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-XXXXX
    Optional:    false
```
Note that the SidecarSet volumes cannot be duplicated with any main container volume names.
Hence you need to use a different volume name to mount the same token. 

Let me know if this satisfies your requirement. 
By the way, v0.2.0 is going to be officially released this week.
