### ISSUE TITLE
[feature request] SidecarSet inject sidecar container to all Pods in some namespaces.

### ISSUE THREAD

**Issue by veophi** [openkruise/kruise#1368]
**What would you like to be added**:
|  SidecarSet with Label Selector |   SidecarSet with Namespace Selector   |  SidecarSet with both Namespace Selector and Label Selector  |  SidecarSet with nothing|
| --------------------------| ------------------------------| ----------------------| -------------------|
| Select Pod by selector | Select Pod by Namespaces | Select Pod by Namespace and Selector |  Not allowed |

``` yaml
Kind: SidecarSet
spec:
  namespaceSelector:
    matchLabels: 
        ns-label-key: ns-label-value
```

or 

``` yaml
Kind: SidecarSet
spec:
  namespace: <ns-you-want-to-inject>
```

**Why is this needed**:
Improve the ease of use for SidecarSet.
