### ISSUE TITLE
[BUG]    A/B Testing Example Indent

### ISSUE THREAD

**Issue by eagle9527** [openkruise/kruise#1376]
https://openkruise.io/zh/rollouts/user-manuals/strategy-ab-testing

A/B Testing releases official example indentation issues
The correct example is as follows

```
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  annotations:
    rollouts.kruise.io/rolling-style: partition
spec:
  objectRef:
    workloadRef:
       apiVersion: apps/v1
       kind: Deployment
       name: workload-demo
  strategy:
    canary:
      steps:
      - replicas: 1
        matches:
        - headers:
          - name: user-agent
            type: Exact
            value: pc
      - replicas: 50%
      - replicas: 100%
      trafficRoutings:
      - service: service-demo
        ingress:
          classType: nginx
          name: ingress-demo
```
