### ISSUE TITLE
SidecarSet doesn't support volumeMount if the volume is create by volumeClaimTemplate in parent pod

### ISSUE THREAD

**Issue by gamer22026** [openkruise/kruise#1381]
**What happened**:
Trying to inject a sidecar in STS to use a volume created by a volumeClaimTemplate. If you add a volumeMount referencing the name in the volumeClaimTemplate, the SidecarSet will complain that no volume exists with this name. Seems the SidecarSet spec is expecting a corresponding volume be created in the sidecar container. However it's perfectly valid for a sidecar container to use a volume name created by a volumeClaimTemplate created in the parent pod

**What you expected to happen**:
Adding a volumeMount to the SidecarSet referencing the volume name from the parent pod's volumeClaimTemplate would mount that volume in the sidecar container

**How to reproduce it (as minimally and precisely as possible)**:
Create sts with a corresponding volumeClaimTemplate
Try to add a volumeMount to the sidecarSet using the volume name from the volumeClaimTemplate

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.4.0
- Kubernetes version (use `kubectl version`): 1.25.12
- Install details (e.g. helm install args):
- Others:

**Comment by zmberg** [comment]
@gamer22026 I think you can't set volumeClaimTemplate.metadata.name, for example:
```yaml
---
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  containers:
    - name: sidecar1
      image: centos:6.7
      command:
        - sleep
        - 999d
      podInjectPolicy: BeforeAppContainer
      shareVolumePolicy:
        type: enabled
      volumeMounts:
        - name: log-volume
          mountPath: "/var/log"
  volumes:
    - name: log-volume
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi

```
