### ISSUE TITLE
[BUG] alter imagepulljob inoperative

### ISSUE THREAD

**Issue by ls-2018** [openkruise/kruise#1386]
After the imagepodjob is completed, the job content is changed and the job is not working
 

## What happened
```
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: job-with-always2
spec:
  image: nginx:1.9.1
  parallelism: 10
  selector:
    names:
      - kind-worker3
```

When the job is done and the selector is removed and reapplied, the job does not work

## What you expected to happen

Pull the image to the desired node
