### ISSUE TITLE
[BUG] BroadcastJob  activeDeadlineSeconds did not take effect

### ISSUE THREAD

**Issue by ls-2018** [openkruise/kruise#1409]
**What happened**:
```
pod is over 300 seconds, but still there
 ```
**What you expected to happen**:
```
pod cleared
 ```

**How to reproduce it (as minimally and precisely as possible)**:
```
echo 'kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "EphemeralContainers": true
nodes:
- role: control-plane
  image: kindest/node:v1.26.0
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.0
  labels:
    zone: c
' >/tmp/kind.yaml

kind create cluster --config /tmp/kind.yaml
kubectl cluster-info --context kind-kind

helm install kruise openkruise/kruise --version 1.4.0


echo 'apiVersion: apps.kruise.io/v1alpha1
kind: BroadcastJob
metadata:
  name: broadcastjob-ttl
spec:
  template:
    spec:
      containers:
        - name: pi
          image: registry.cn-hangzhou.aliyuncs.com/acejilam/tensorflow:latest-gpu     # 5.7G
      restartPolicy: OnFailure
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 300
    ttlSecondsAfterFinished: 300
  paused: false
  parallelism: 3
' >/tmp/bcj.yaml
kubectl apply -f /tmp/bcj.yaml

```
**Anything else we need to know?**:
```
But it doesn't happen every time, and I've found that when the watch pod, node, or BroadcastJob have no events, the tuning logic doesn't fire
 
```
**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

<img width="556" alt="image" src="https://github.com/openkruise/kruise/assets/38821215/fcbd5228-fd21-4455-8dab-075464f1e314">
<img width="674" alt="image" src="https://github.com/openkruise/kruise/assets/38821215/b81d3e45-9842-4e2c-98ca-e6b521f7378f">
<img width="1502" alt="image" src="https://github.com/openkruise/kruise/assets/38821215/480ea917-7ed9-4404-aa16-7c403ef119a5">

I changed the activeDeadlineSeconds to 30 seconds, and I did it again.
  
<img width="524" alt="image" src="https://github.com/openkruise/kruise/assets/38821215/f86adcdb-9398-49e0-a3d8-2a912c06fbe0">
