### ISSUE TITLE
[BUG] Cloneset InPlaceUpdate  did not create ImagePullJobs

### ISSUE THREAD

**Issue by wanglishuang** [openkruise/kruise#1419]
**What happened**:
Cloneset InPlaceUpdate  did not create ImagePullJobs as I expeted.

cluster info:
featureGates="PreDownloadImageForInPlaceUpdate=true" 
spec/replicas: 20
spec/updateStrategy/type: InPlaceIfPossible
spec/scaleStrategy/maxUnavailable: 4

most important info: 
I repeatly used an old image which has been manually delete on the nodes.

**What you expected to happen**:
Should create ImagePullJobs even if update cloneset with an old image .

**How to reproduce it (as minimally and precisely as possible)**:
It's easy to reproduce:
Prepare two image versions for your test app, let's say image1 and image2 ;
apply your cloneset with  image1;
update your cloneset to  image2; // here will create ImagePullJobs , no problem
log in the nodes (or use other bach delete methods );
```
docker rmi `docker images |awk '{print $3}'`   ; // delete unused images
```
repeatly update your cloneset  back to  image1; // here will not create ImagePullJobs 

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- V1.40
- Kubernetes version (use `kubectl version`):
- v1.16.15
- Install details (e.g. helm install args):
- Others:

**Comment by ls-2018** [comment]
can you provide the complete yaml file and the interval between changing the image, which will help me troubleshoot the problem.

**Comment by wanglishuang** [comment]
> can you provide the complete yaml file and the interval between changing the image, which will help me troubleshoot the problem.

1,  create cloneset 
kubectl apply -f sample_1.yaml 
replicas: 5  ( in-place update requires  replicas>3 )
partition: 1  ( in-place update requires  gray update )
image: nginx:1.10
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  annotations:
    apps.kruise.io/image-predownload-parallelism: "2"
  labels:
    group: test-group
    service: sample
  name: sample
  namespace: sample-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      group: test-group
      service: sample
  updateStrategy:
    type: InPlaceIfPossible
    partition: 1
    maxSurge: 0
    maxUnavailable: 1
  template:
    metadata:
      labels:
        group: test-group
        service: sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.10
      nodeSelector:
        sample/group: sample-cloneset
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - sample
              topologyKey: "kubernetes.io/hostname"
```
2, update image to nginx:1.20
kubectl apply -f sample_2.yaml 
image: nginx:1.20
No problem : created ImagePullJobs  for image: nginx:1.20 .

```
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  creationTimestamp: '2023-09-19T08:13:08Z'
  generation: 1
  labels:
    controller.kubernetes.io/hash: c8c648d78
    group: test-group
    service: sample
  name: sample-c8c648d78-nginx
  namespace: sample-ns
  ownerReferences:
    - apiVersion: apps.kruise.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: CloneSet
      name: sample
      uid: f90b9add-904c-4889-80a3-fbf95e263de8
  resourceVersion: '7540715271'
  selfLink: >-
    /apis/apps.kruise.io/v1alpha1/namespaces/sample-ns/imagepulljobs/sample-c8c648d78-nginx
  uid: b6b51f8a-79ac-4894-b50e-d05877fde888
status:
  active: 2
  desired: 5
  failed: 0
  message: job is running, progress 0.0%
  startTime: '2023-09-19T08:13:08Z'
  succeeded: 0
spec:
  completionPolicy:
    ttlSecondsAfterFinished: 600
    type: Always
  image: nginx:1.20
  parallelism: 2
  podSelector:
    matchExpressions:
      - key: controller-revision-hash
        operator: NotIn
        values:
          - sample-c8c648d78
          - c8c648d78
    matchLabels:
      group: test-group
      service: sample
  pullPolicy:
    backoffLimit: 1
    timeoutSeconds: 300
```

3, update back to nginx:1.10
kubectl apply -f sample_1.yaml 
image: nginx:1.10
Problem occurs:  did not create ImagePullJobs  for image: nginx:1.10 again.

Because we use a cron job to delete unused images on nodes everyday, so in another day if we want to update back to an earlier image , kruise will not create ImagePullJobs for the old image, the update speed will be slower.

---
By the way , the auto-created ImagePullJobs  for cloneset in-place update ,  did not inherit nodeSelector of cloneset .  It just has a podSelector ,which is inherited from cloneset's selector.
Why not use the intersection of these two conditions ?
```
      nodeSelector:
        sample/group: sample-cloneset
```
