### ISSUE TITLE
[feature request] UnitedDeployment supports capacity planning to subset.

### ISSUE THREAD

**Issue by veophi** [openkruise/kruise#1427]
**What would you like to be added**:
```yaml
kind: UnitedDeployment
spec:
 replicas: 4
 topology:
   subsets:
   - name:  default-pool
     capacity:
       min: 2
       max: 4
   - name: spot-pool
     capacity:
       min: 0
       max: 2
  - name: elastic-pool
     capacity:
         min: 0
```
The 4 replicas of UD will be scheduled to default-pool;

If users scale up UD from 4 to 7:
- 2 new replicas will be scheduled to spot-pool;
- 1 new replicas will be scheduled to elastic-pool;

**Why is this needed**:
Subset capacity planning can be done in advance, and users just update `spec.replicas` field of UD when scaling up.
