### ISSUE TITLE
[feature request] support volumeMount injection to target pod's other container(s) in SidecarSet

### ISSUE THREAD

**Issue by sheronw** [openkruise/kruise#1455]
**What would you like to be added**:
As of OpenKruise 1.6, `shareVolumePolicy` is available for mount main container volumes to sidecar container, and `transferEnv` is available to transfer env from main container from sidecar container. Those are all single direction sharing from main container to sidecar container. We hope the opposite approach, *which is injecting volumeMount of sidecar container to main application container*, could also be possible. In theory, it could be implemented by adding required volumeMounts during container merge period in sidecarset's pod mutating webhook.

In #939 , a similar feature request, another community member proposed to add one field called `addMount` under init container. We believe one explicit volumeMount definition injected to main container should be defined outside of the container scope and thus here we have two proposals:

1. Add the target container name and volume definition under sidecarset spec, so that we could parse this from API and inject volumeMount definition when [main app container is merged](https://github.com/openkruise/kruise/blob/01717ff47d1247f4b1ccc1caf74272f64daf33a2/pkg/webhook/pod/mutating/sidecarset.go#L257).
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sidecarset-test
spec:
  selector:
    matchLabels:
      app: xxx
  initContainers:
    - name: init-agent-container
      image: xxxagent:xxx
      command: [ "/bin/sh", "-c", "initenv.sh" ]
      volumeMounts:
        - name: xxx-agent-vol
          mountPath: ~/.opt/sandbox/
  volumes:
    - name: xxx-agent-vol
      emptyDir: { }
  targetContainerInjection:
    addMount:
        - targetContainerName: xxx # this will add volume xxx-agent-vol to container xxx
          name: xxx-agent-vol
          mountPath: ~/.opt/sandbox/
```
2. As the goal to inject volumeMount is usually to make communications happen between sidecar and main containers, simply add a flag under sidecar container to make its volumes available to other containers already in the pod. This approach could be implemented the same way as current `shareVolumePolicy` ([calculate a list of volumeMounts](https://github.com/openkruise/kruise/blob/01717ff47d1247f4b1ccc1caf74272f64daf33a2/pkg/control/sidecarcontrol/util.go#L319) that needs to be attached and use this to update main container).
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sidecarset-test
spec:
  selector:
    matchLabels:
      app: xxx
  containers:
    - name: container-1
      image: xxxagent:xxx
      command: [ "/bin/sh", "-c", "initenv.sh" ]
      volumeMounts:
        - name: xxx-agent-vol
          mountPath: ~/.opt/sandbox/
      injectVolumeMount: true # this will copy the volume mount above to all other containers already in pod
  volumes:
    - name: xxx-agent-vol
      emptyDir: { }
```
Env could be shared in a similar approach.

**Why is this needed**:
We are currently working on one sidecar operator that:
- needs to accommodate pods created by different k8s operator systems, it is not feasible to add the volumeMount needed to Pods created by different sources
- while still provides a unified communicate protocol among all containers (currently, Unix Domain Socket via VolumeMount)

We plan to create one mutating webhook that could patch one volumeMount to pods directly as workaround, but still open to further design discussion and have extra bandwidth to contribute if this proposal could be accepted. Please let us know if one formal proposal before PR is required, as this change is related to SidecarSet's API.
