### ISSUE TITLE
[BUG] error when creating "sidecarset.yaml": admission webhook "vsidecarset.kb.io" denied the request: [spec.volumes[0].name: Required value, spec.containers[0].volumeMounts[0].name: Not found: "log-volume"]

### ISSUE THREAD

**Issue by yhadyh** [openkruise/kruise#1459]
yaml模板如下
```
# sidecarset.yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  containers:
  - name: sidecar1
    image: centos:6.7
    command: ["sleep", "999d"] # do nothing at all
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes: # this field will be merged into pod.spec.volumes
  - name: log-volume
    emptyDir: {}
```
```
$ kubectl apply -f sidecarset.yaml
Error from server: error when creating "sidecarset.yaml": admission webhook "vsidecarset.kb.io" denied the request: [spec.volumes[0].name: Required value, spec.containers[0].volumeMounts[0].name: Not found: "log-volume"]
```

**Environment**:
- Kruise version: 1.5.0
- Kubernetes version (use `kubectl version`): 1.23.0
- Install details (e.g. helm install args): helm install kruise openkruise/kruise --version 1.5.0
- Others:
   k8s安装方式：kubeadm manifest 
   网络组件 cilium bgp
