### ISSUE TITLE
[BUG] cloneset scaling down failed (manually/automatically) when minReadySeconds is set big

### ISSUE THREAD

**Issue by myname4423** [openkruise/kruise#1478]
**What happened**: cloneset scaling down failed (manually / automatically) when minReadySeconds is set big, like 99999. spec.replicas of the cloneset is patched as expectedly, but the pods keep unremoved

**What you expected to happen**: deployment in the same setting could scale down successfully

**How to reproduce it (as minimally and precisely as possible)**: 
cloneset.yaml here:
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample
  minReadySeconds: 99999
  updateStrategy:
    type: ReCreate
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: openresty
        image: openresty/openresty:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m" 
          limits:
            cpu: "500m"
```
first, `kubectl apply -f cloneset.yaml`
after the pods ready, `kubectl scale cloneset/sampe --replicas=3`
**Anything else we need to know?**: 
1. After `kubectl patch cloneset sample --type=merge -p '{"spec":{"minReadySeconds":null}}'`, problem solved. 
2. Deployment scales down well in the same setting

**Environment**:
- Kruise version:1.5.1
- Kubernetes version (use `kubectl version`): v1.28.3
- Install details (e.g. helm install args): none
- Others: none
