### ISSUE TITLE
[BUG] AdvanceCronJob keep on recreating BroadcastJobs (pods) on all nodes. 

### ISSUE THREAD

**Issue by mehuaniket** [openkruise/kruise#1488]
**What happened**:

I'm trying to deploy AdvanceCronJob with following template. It should only run once around time provided.
```
# Source: k8slogpusher/charts/k8slogpusher-base/templates/logpusher.yaml
apiVersion: apps.kruise.io/v1alpha1
kind: AdvancedCronJob
metadata:
  name: k8slogpusher-post-k8slogpusher-base-adj-log-pusher
  namespace: logspusher
  labels:
    helm.sh/chart: k8slogpusher-base-1.5.1
    app.kubernetes.io/name: k8slogpusher-base
    app.kubernetes.io/instance: k8slogpusher-post
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "*/30 * * * *"
  template:
    broadcastJobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
            - image: ubuntu:latest
              name: log-pusher
              command:
                - /bin/bash
                - -c
                - /script/log-pusher.sh
              env:
              - name: NODE_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: BUCKET_NAME
                value: bucket-name
              volumeMounts:
              - mountPath: /var/log
                name: logs-dir
              - mountPath: /script
                name: script-volume
            volumes:
            - configMap:
                defaultMode: 511
                name: k8slogpusher-post-k8slogpusher-base-log-pusher-configmap
              name: script-volume
            - hostPath:
                path: /var/log
              name: logs-dir
        completionPolicy:
          ttlSecondsAfterFinished: 300
          type: Always
        failurePolicy:
          type: FailFast
          restartLimit: 2
```
**What you expected to happen**:

I expected that it should only run once and it should run again on schedule time. 

**How to reproduce it (as minimally and precisely as possible)**:

Try applying AdvanceCronJob with BraodCastJobTemplate with completion policy. You can reproduce these. 

**Environment**:
- Kruise version: 1.5.1
- Kubernetes version (use `kubectl version`): 1.27.8
- Install details (e.g. helm install args): none
- Others:

**Comment by aniketexplorex** [comment]
```
# Source: k8slogpusher/charts/k8slogpusher-base/templates/logpusher.yaml
apiVersion: apps.kruise.io/v1alpha1
kind: AdvancedCronJob
metadata:
  name: k8slogpusher-post-k8slogpusher-base-adj-log-pusher
  namespace: logspusher
  labels:
    helm.sh/chart: k8slogpusher-base-1.5.1
    app.kubernetes.io/name: k8slogpusher-base
    app.kubernetes.io/instance: k8slogpusher-post
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "*/30 * * * *"
  template:
    broadcastJobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
            - image: ubuntu:latest
              name: log-pusher
              command:
                - /bin/bash
                - -c
                - /script/log-pusher.sh
              env:
              - name: NODE_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: BUCKET_NAME
                value: bucket-name
              volumeMounts:
              - mountPath: /var/log
                name: logs-dir
              - mountPath: /script
                name: script-volume
            volumes:
            - configMap:
                defaultMode: 511
                name: k8slogpusher-post-k8slogpusher-base-log-pusher-configmap
              name: script-volume
            - hostPath:
                path: /var/log
              name: logs-dir
        completionPolicy:
          ttlSecondsAfterFinished: 300
          type: Always
        failurePolicy:
          type: FailFast
          restartLimit: 2
```
