### ISSUE TITLE
[BUG] ImagePullJob delayed for five minutes.

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1528]
**What happened**:
ImagePullJob delayed for five minutes.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create ImageListPullJob for nginx and busybox:
```yaml

apiVersion: apps.kruise.io/v1alpha1
metadata:
  name: test-imagelistpulljob
spec:
  images:
    - registry.k8s.io/e2e-test-images/nginx:1.14-4
    - registry.k8s.io/e2e-test-images/busybox:1.29-4
  parallelism: 4
  pullPolicy:
    timeoutSeconds: 50
    backoffLimit: 2
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 50
    ttlSecondsAfterFinished: 20
  imagePullPolicy: Always
```
This will create imagepulljob-1 for image nginx:1.14-4 and imagepulljob-2 for image busybox:1.29-4
2. ImagePullJob controller reconcile imagepulljob-1, and sync nginx:1.14-4 to NodeImage worker-1.
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: NodeImage
metadata:
  name: worker-1
spec:
  images:
    nginx:
      tags:
        - createdAt: "2024-03-20T02:14:49Z"
          pullPolicy:
            activeDeadlineSeconds: 50
            backoffLimit: 2
            timeoutSeconds: 50
            ttlSecondsAfterFinished: 570
          tag: 1.14-4
```
Also, to prevent frequent Updates, add the NodeImage to the Expectation with the following code:
![image](https://github.com/openkruise/kruise/assets/25051767/29073666-2c37-441e-81a0-76961b021281)
3. ImagePullJob controller reconcile imagepulljob-2, and the above update of NodeImage work-1 is not synchronized back to Kruise Cache, then will be requeued.
![image](https://github.com/openkruise/kruise/assets/25051767/3c6d182a-2722-431f-a310-a9c0558ccb9b)
4. NodeImage worker-1 synchronized back to Kruise Cache, but since the NodeImage work-1 doesn't contain the image busybox:1.29-4, it doesn't trigger the ImagePullJob imagepulljob-2  reconcile.
![image](https://github.com/openkruise/kruise/assets/25051767/4c240e08-d19f-45f7-9548-6dc98903c129)
5. ImagePullJob controller reconcile imagepulljob-2 with the above 5 mins
![image](https://github.com/openkruise/kruise/assets/25051767/1c2e106c-7508-4363-bae7-8a5439cd35da)

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
