### ISSUE TITLE
[feature request] Kruise-daemon is not deployed on virtual-kubelet node.

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1596]
**What would you like to be added**:
Kruise-Daemon mainly provides image warming, container restart and other capabilities, its working mechanism is through the containerd cri interface interaction.

Kruise-Daemon doesn't really work on virtual-kubelet nodes, so you can skip the virtual-kubelet node when deploying. For examples:
```yaml
daemon:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: NotIn
          values:
          - virtual-kubelet
```
related code: https://github.com/openkruise/charts/blob/master/versions/kruise/1.6.2/values.yaml

**Why is this needed**:
