### ISSUE TITLE
[BUG] Advanced StatefulSet In situ upgrade card owner

### ISSUE THREAD

**Issue by ls-2018** [openkruise/kruise#1606]
```
apiVersion: apps.kruise.io/v1beta1
kind: StatefulSet
metadata:
  name: "ss-test"
  namespace: "default"
  annotations:
    apps.kruise.io/image-predownload-parallelism: "10"
    apps.kruise.io/image-predownload-min-updated-ready-pods: "3"
spec:
  podManagementPolicy: Parallel   # OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 40%           
      paused: false 

      podUpdatePolicy: InPlaceIfPossible # InPlaceIfPossible # ReCreate、InPlaceOnly

  replicas: 10
  reserveOrdinals:
    - 1
  serviceName: fake-service
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
        'example.io/unready-predelete-blocker': 'true'
        'example.io/unready-inplaceupdate-blocker': 'true'
    spec:
      terminationGracePeriodSeconds: 5
      readinessGates:
        - conditionType: InPlaceUpdateReady
      containers:
        - name: main
          image: centos:8
          command:
            - "sleep"
            - "1d"
  lifecycle:
    preDelete:
      labelsHandler:
        example.io/unready-predelete-blocker: "true"
      markPodNotReady: true
    inPlaceUpdate:
      labelsHandler:
        example.io/unready-inplaceupdate-blocker: "true"
      markPodNotReady: true

 
 

```

**What happened**:
```
When I load image from centos:8 -&gt; centos:7, and the two images exist on all nodes in the cluster.
We can find four pods with InPlaceUpdateReady =False conditions.
When we remove the 'example.io/unready-inplaceupdate-blocker' tag, after a while we can see that the pod is ready, but the rest of the pod has not been updated
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.6.0
- Kubernetes version (use `kubectl version`):
```
Cluster installed with kind
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.15
WARNING: version difference between client (1.29) and server (1.24) exceeds the supported minor version skew of +/-1
```
- Install details (e.g. helm install args):
- ```
helm install kruise openkruise/kruise --version 1.6.0 --set manager.image.repository=openkruise-registry.cn-shanghai.cr.aliyuncs.com/openkruise/kruise-manager
```
- Others:
```
Operation procedure 
k apply -f sa.yaml 
change image
k apply -f sa.yaml 
```
