### ISSUE TITLE
[feature request]  the rescheduleCriticalSeconds range is too small.

### ISSUE THREAD

**Issue by rouroumaibing** [openkruise/kruise#1622]
**What would you like to be added**:
https://github.com/openkruise/kruise/tree/master/pkg/webhook/workloadspread/validating/workloadspread_validation.go

MaxScheduledFailedDuration = 300 * time.Second

This value is too small, resulting in rescheduleCriticalSeconds not exceeding a maximum of 147
I need a larger interval。 like 240.

**Why is this needed**:

I refer to this document in Huawei Cloud operation, due to the node creation time on almost 4-5 minutes, resulting in the pod are finally deployed to the subset-c, not the subset-b（no pod）

https://openkruise.io/zh/docs/user-manuals/workloadspread/

```
apiVersion: apps.kruise.io/v1alpha1
kind: WorkloadSpread
metadata:
  name: workloadspread-demo
spec:
  targetRef:
    apiVersion: apps.kruise.io/v1alpha1
    kind: CloneSet
    name: sample
  subsets:
    - name: subset-a
      requiredNodeSelectorTerm:
        matchExpressions:
          - key: cpu-label
            operator: In
            values:
              - "001"
      tolerations: [ ]
    - name: subset-b
      requiredNodeSelectorTerm:
        matchExpressions:
          - key: cpu-label
            operator: In
            values:
              - amd
    - name: subset-c
      requiredNodeSelectorTerm:
        matchExpressions:
          - key: cpu-label
            operator: In
            values: 
              - intel
  scheduleStrategy:
    type: Adaptive
    adaptive:
      rescheduleCriticalSeconds: 240  // i change MaxScheduledFailedDuration to  30000* time.Second. it's work!
```
