### ISSUE TITLE
[BUG] failed calling webhook "mcloneset.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-cloneset?timeout=30s": EOF

### ISSUE THREAD

**Issue by xlcbingo1999** [openkruise/kruise#1652]
**What happened**: I got the error as below.

```
error from server (InternalError): error when creating "/root/test_k8s/kruise/config/samples/apps_v1alpha1_cloneset.yaml": Internal error occurred: failed calling webhook "mcloneset.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-cloneset?timeout=30s": EOF
```

**What you expected to happen**: Deploy a sample cloneset normally.

**How to reproduce it (as minimally and precisely as possible)**:

First, I was in **default** namespace, and used helm to install a new kruise. My install code:

```
helm install kruise openkruise/kruise --version 1.6.3
```

Second, I got the success message about install the kruise.

```
# helm status kruise
NAME: kruise
LAST DEPLOYED: Thu Jun 27 20:55:31 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

Third, I apply  a cloneset in default namespace:

```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: main
        image: nginx:alpine
  updateStrategy:
    type: InPlaceIfPossible
    maxUnavailable: 2
```

Fourth, I got error

```
error from server (InternalError): error when creating "/root/test_k8s/kruise/config/samples/apps_v1alpha1_cloneset.yaml": Internal error occurred: failed calling webhook "mcloneset.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-cloneset?timeout=30s": EOF
```

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.6.3
- Kubernetes version (use `kubectl version`): v1.25.16
- Install details (e.g. helm install args): helm install kruise openkruise/kruise --version 1.6.3
- Others: None
