### ISSUE TITLE
[feature request] support pvc update when volumeClaimTemplates storage size changed in cloneset

### ISSUE THREAD

**Issue by basuotian** [openkruise/kruise#1670]
**What would you like to be added**:

We are using csi ephemeral volumes in cloneset with some csi implement support `VolumeExpansion`, the cloneset like 

```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: my-hello-world
  namespace: default
spec:
  // ...
  updateStrategy:
    type: InPlaceIfPossible
  volumeClaimTemplates:
  - metadata:
      name: data-dir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 40Gi // from 30Gi patch to 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   // ...
  name: data-dir-my-hello-world-gv7w7
  // ...
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi  // need to be patched
  // ...
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  phase: Bound
```
When we update storage from 30Gi to 40Gi, the cloneset is updated but pvc still requests 30Gi,
looks like kruise controller dose not patch pvc as the latest volumeClaimTemplate.

Finally we have to patch pvc manually to improve volume resize, we think pvc shoule be patched by kruise as the volumeClaimTemplate updated in cloneset

**Why is this needed**:
