### ISSUE TITLE
[BUG] Sidecarset sourceContainerNameFrom 并不支持name,namespace

### ISSUE THREAD

**Issue by magicsong** [openkruise/kruise#1735]
**What happened**:
https://github.com/pigletfly/kruise/blob/6a62320848f8e10e037c747eeef6b99552af7fa9/pkg/control/sidecarcontrol/util.go#L434
**What you expected to happen**:
这里hardcode枚举了，仅仅支持labels和annoation，sidecar无法获取自己的name,namepsace
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: 最新代码
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by magicsong** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/pods/helpers.go 更新一下代码是不是就可以了

**Comment by ABNER-1** [comment]
看起来是的，你愿意同步一下这段代码贡献一下吗？
如果可以的话可以将这几个case 加到对应的 ut 中。

**Comment by furykerry** [comment]
it is strange to use pod name and namespace as part of the container name , are there any reason of this usage? @magicsong

**Comment by magicsong** [comment]
> it is strange to use pod name and namespace as part of the container name , are there any reason of this usage? @magicsong

"sourceContainerNameFrom should be a mechanism similar to the downward API, used to mount pod metadata to environment variables, rather than its literal name meaning."

**Comment by furykerry** [comment]
> "sourceContainerNameFrom should be a mechanism similar to the downward API, used to mount pod metadata to environment variables, rather than its literal name meaning."
so what field do you need the complete downward api ? it make no sense to make sourceContainerNameFrom refer to the pod name. Do you mean other fields? TransferEnv can refer to the environment name of another container, this environment can use downward api.

**Comment by magicsong** [comment]
> > "sourceContainerNameFrom should be a mechanism similar to the downward API, used to mount pod metadata to environment variables, rather than its literal name meaning."
> 
> so what field do you need the complete downward api ? it make no sense to make sourceContainerNameFrom refer to the pod name. Do you mean other fields? TransferEnv can refer to the environment name of another container, this environment can use downward api.

The sidecar needs to have the ability to know its own name and namespace without interfering with the main container. Not all main containers have the environment variables PodName and PodNamespace, and the names are fixed.

Additionally, the OpenKruise documentation mentions support for [metadata.name], but it is not actually supported.

**Comment by furykerry** [comment]
> The sidecar needs to have the ability to know its own name and namespace without interfering with the main container. Not all main containers have the environment variables PodName and PodNamespace, and the names are fixed.

you do not need to use transferEnv for this purpose, you can just use downward api related environment in the container part of sidecarset (sidecarset.spec.containers[*].env[*].valueFrom.fieldRef.fieldPath )

**Comment by magicsong** [comment]
> > The sidecar needs to have the ability to know its own name and namespace without interfering with the main container. Not all main containers have the environment variables PodName and PodNamespace, and the names are fixed.
> 
> you do not need to use transferEnv for this purpose, you can just use downward api related environment in the container part of sidecarset (sidecarset.spec.containers[_].env[_].valueFrom.fieldRef.fieldPath )

maybe you could have a try. it will be rejected

**Comment by furykerry** [comment]
you can try this example
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  # matchExpressions:
  # - {key: tier, operator: In, values: [frontend, middleware]}
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  containers:
  - name: sidecar1
    image: centos:6.7
    command: ["sleep", "999d"] # do nothing at all
    env:
    - name: podName
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes: # this field will be merged into pod.spec.volumes
  - name: log-volume
    emptyDir: {}
```
