### ISSUE TITLE
[feature request] In-place update specified container without marking pod not ready

### ISSUE THREAD

**Issue by ABNER-1** [openkruise/kruise#1808]
**What would you like to be added**:

Enable users to control whether a pod should be marked as unready during an in-place update.

**Why is this needed**:

In Kruise, we have introduced the InPlaceUpdateReady readiness gate, which is set to not ready before initiating an in-place update for a container. 

When utilizing Kruise to perform in-place updates on less critical containers, there is a limitation: even if you configure the CloneSet lifecycle, you cannot prevent the pod from being marked as not ready during the update process.

**Comment by jairuigou** [comment]
Hi, Is there any progress on this? I think we might need to determine in `CalculateSpec` whether to skip marking the Pod as NotReady based on the container names involved in this in-place update. These container names can be configured under lifecycle, for example:
```
lifecycle:
  inPlaceUpdate:
    markPodNotReady: true
    finalizersHandler:
    - example.io/unready-blocker
    ignoreContainersForReady:
    - container1
    - container2
```
