### ISSUE TITLE
[BUG] SidecarSet maxunvailable=5% and matched pods = 6, but upgrade block.

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1812]
**What happened**:
I1104 09:45:44.530512       1 sidecarset_controller.go:93] Observed updated Spec for SidecarSet: /clickhouse-exporter
I1104 09:45:44.530582       1 sidecarset_controller.go:141] begin to process sidecarset clickhouse-exporter for reconcile
I1104 09:45:44.548081       1 sidecarset_processor.go:270] sidecarSet(clickhouse-exporter) update status(MatchedPods:6, UpdatedPods:0, ReadyPods:6, UpdatedReadyPods:0) success
I1104 09:45:44.548324       1 sidecarset_strategy.go:85] sidecarSet(clickhouse-exporter) matchedPods(6) waitUpdated(6) notUpgradable(0)
I1104 09:45:44.548388       1 sidecarset_processor.go:174] sidecarSet next update is nil, skip this round, name: clickhouse-exporter

```
  updateStrategy:
    maxUnavailable: 5%
    partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  latestRevision: xxxxx-f4686f8b6
  matchedPods: 6
  observedGeneration: 4
  readyPods: 6
  updatedPods: 0
  updatedReadyPods: 0
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: 1.5.x
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
