### ISSUE TITLE
[feature request] How to restart all pods in a cloneset, just restart not create new pods and delete old pods

### ISSUE THREAD

**Issue by bellondr** [openkruise/kruise#1826]
Hi guys, I am a DevOps form Jerry.ai.
I want to know How to restart all pods in a cloneset ? just restart not create new pods and delete old pods
Use ContainerRecreateRequest is too complex that need to create as many ContainerRecreateRequest as pods.
https://openkruise.io/zh/blog/openkruise-0.9.0/

**What would you like to be added**:
Is there a command like `kubectl rollout restart CloneSet  demo` to restart all pods?

**Why is this needed**:

**Comment by furykerry** [comment]
ContainerRecreateRequest(CRR) is for restarting a single container in a pod ( pod may have multiple containers). Initiating multiple CRR from kruise cli is a possible solution for you case, but it do has some problems. In particular, restarting a container from all pods in a cloneset can make the service unavailable temporally . Safer solution is to modify the podtemplate in cloneset and triggering an inplace update. the cloneset controller will respect the maxUnavailable setting during inplace-update. It is possible to trigger inplace-update without changing the image in podtemplate, one can setup a downward api backed environment, and change the corresponding annotation, e.g.
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  ...
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        RESTART-TRIGGER: "... arbitrary timestamp or random string ..."
    spec:
      containers:
      - name: sidecar
        env:
        - name: RESTART-TRIGGER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['RESTART-TRIGGER']
      - name: main
        image: main-image:v1
  updateStrategy:
    type: InPlaceIfPossible
```

you can refer to the doc for more information about inplace-update the container environment
https://openkruise.io/docs/core-concepts/inplace-update#understand-inplaceifpossible
