### ISSUE TITLE
[BUG] A smaller MaxUnavailable will block the sidecarSet from updating Pods.

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1832]
**What happened**:
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  containers:
  - command:
    - sleep
    - 999d
    image: mirrors-ssl.aliyuncs.com/centos:6.8
    imagePullPolicy: IfNotPresent
    name: sidecar1
    podInjectPolicy: BeforeAppContainer
    resources: {}
    shareVolumePolicy:
      type: disabled
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    upgradeStrategy:
      upgradeType: ColdUpgrade
  injectionStrategy: {}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    maxUnavailable: 5%
    partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  latestRevision: test-sidecarset-7658c89f8d
  matchedPods: 5
  observedGeneration: 3
  readyPods: 5
  updatedPods: 0
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
