### ISSUE TITLE
[BUG] PyTorchJob create pod failure due to pod webhook

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#1863]
**What happened**:
1. create PyTorchJob
```
apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: pytorch-tcp-dist-mnist
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            app: tfjob
        spec:
          terminationGracePeriodSeconds: 0
          containers:
            - command: [ "/bin/sleep", "infinity" ]
              image: busybox:latest
              name: pytorch
```
2. describe PyTorchJob
```
  Warning  FailedCreatePod  108s (x17 over 7m15s)  pytorchjob-controller  Error creating: admission webhook "mpod.kb.io" denied the request: Internal error occurred: the spec replicas field ".spec.pytorchReplicaSpecs.Worker.replicas" does not exist
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: v1.6.3
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
