### ISSUE TITLE
[BUG] remove the matched labels when rolling update for daemonset not working

### ISSUE THREAD

**Issue by Kuromesi** [openkruise/kruise#1871]
**What happened**:
I was using advanced daemonset with updateStrategy like below and modify the image tag to start upgrading, when I added label `nodeType=canary` to a node, it works fine and pod on this node is updated. However, when I tried to remove the label on this node, the pod is not updated.
```yaml
updateStrategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
      rollingUpdateType: Standard
      selector:
        matchLabels:
          nodeType: canary
```
**What you expected to happen**:
I'm not sure if this is a bug or designed like this, but what I expected to happen is when the label was removed, the pod should be updated to the old revision instead of keeping the new revision.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
