### ISSUE TITLE
Rolling update failed

### ISSUE THREAD

**Issue by yiqinguo** [openkruise/kruise#196]
**What happened**:

```
apiVersion: apps.kruise.io/v1alpha1
kind: StatefulSet
metadata:
  name: sample
spec:
  replicas: 3
  serviceName: fake-service
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      readinessGates:
         # A new condition that ensures the pod remains at NotReady state while the in-place update is happening
      - conditionType: InPlaceUpdateReady
      containers:
      - name: main
        image: nginx:alpine
  podManagementPolicy: Parallel # allow parallel updates, works together with maxUnavailable
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      # Do in-place update if possible, currently only image update is supported for in-place update
      podUpdatePolicy: InPlaceIfPossible
      # Allow parallel updates with max number of unavailable instances equals to 2
      maxUnavailable: 20%
```

When rolling updates, the maxUnavailable value is 20%, and the replicas value is 3. After updating an instance, the next rolling update cannot be carried out.

**What you expected to happen**:

All instances can be updated on a rolling basis.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/12421121/71308556-1a3a8500-2439-11ea-8c10-ef8c7a5f7130.png)
I think the minimum value calculated by maxUnavailable here should be 1.

**Environment**:
- Kruise version:latest
- Kubernetes version (use `kubectl version`): 1.15.3
- OS (e.g: `cat /etc/os-release`): centos7
