### ISSUE TITLE
[BUG] use sidecarset inject init container failed

### ISSUE THREAD

**Issue by song0071000** [openkruise/kruise#2013]
**What happened**:
use sidecarset inject init container failed, the error message is 
`        
        Pod "accesshub-logic-test-fz4qh" is invalid:
        spec.initContainers[0].name: Duplicate value: "sidecar1"
`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
cloneset yaml

```
spec:
  replicas: 1
  revisionHistoryLimit: 10
  scaleStrategy: {}
  selector:
    matchLabels:
      app.kubernetes.io/instance: xx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: xx
    spec:
      containers:
        - args:
            - bash
            - '-c'
            - ./vitohuang-test
          command:
            - dumb-init
            - '--'
          image: xxx
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - '-c'
                  - /poststart.sh
            preStop:
              exec:
                command:
                  - bash
                  - '-c'
                  - /prestop.sh
          name: accesshub-logic-test
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/pod-state
              name: pod-state
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.annotations['xxx/pod-state'']'
                path: pod-state
          name: pod-state
  updateStrategy:
    inPlaceUpdateStrategy: {}
    maxSurge: 0
    maxUnavailable: 1
    partition: 0%
    type: InPlaceOnly
```

sidecarset yaml
```
spec:
  initContainers:
    - command:
        - sleep
        - '1'
      image: busybox
      imagePullPolicy: Always
      name: sidecar1
      podInjectPolicy: BeforeAppContainer
      resources: {}
      shareVolumePolicy: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      upgradeStrategy: {}
      volumeMounts:
        - mountPath: /var/log
          name: log-volume
  injectionStrategy: {}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: xx
  updateStrategy:
    maxUnavailable: 1
    partition: 0
    type: RollingUpdate
  volumes:
    - emptyDir: {}
      name: log-volume
```

**Anything else we need to know?**:

**Environment**:
- Kruise version: 
    v1.4.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.3-aliyun.1", GitCommit:"717c81c3a51aae15be22575e81cdb2aafcceb3de", GitTreeState:"clean", BuildDate:"2025-03-12T02:32:13Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.26) exceeds the supported minor version skew of +/-1
```
- Install details (e.g. helm install args):
- Others:
