### ISSUE TITLE
[feature request] CloneSet selective Pod deletion support label selector

### ISSUE THREAD

**Issue by fatedier** [openkruise/kruise#264]
**What would you like to be added**:
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
spec:
  # ...
  replicas: 4
  scaleStrategy:
    podsMatchSelectorToDelete:
      matchLabels:
        test-key: foo
```

**Why is this needed**:
CloneSet now supports `podsToDelete` to specify which pod to delete first. It requires users to update CloneSet spec manually. It's ok if user want to scale down pods in the same time.

To condiser another scenario：
We want to drain one node and migrate its pods to others and we prefer create new pod first and then delete old pod to keep enough ready pods.

The process we want:
1. Cordon node.
2. Label pods in this node `test-key: foo`.
3. Wait CloneSet controller create new pods and delete pods with label `test-key: foo`.
4. Do something on this node.
5. Uncordon node.

To achieve the process above, we should not only support `podsMatchSelectorToDelete`, but also consider follow the `maxSurge` and `maxUnavailable` in `updateStrategy`.

For `maxUnavailable=0, maxSurge=1` and there are 5 pods to delete, we should recreate pod one by one and create new pod first.

For `maxUnavailable=1, maxSurge=0`, we should delete pods first.

If so, maybe we can define `maxSurge` and `maxUnavailable` outside `updateStrategy` or create a new struct for them.
/cc @FillZpp
