### ISSUE TITLE
[feature request] Pre-hook and post-hook on Pod in-place upgrading

### ISSUE THREAD

**Issue by Yetsenn** [openkruise/kruise#298]
**What would you like to be added**:
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
spec:
  # ...
  lifecycle:
    update:
      labels:
        foo.io/handler: "true"
```

```
kind: Pod
metadata:
  labels:
    lifecycle.apps.kruise.io/state: Running
```

**Why is this needed**:
Before patching a pod when upgrading images in a cloneSet, in order to download data first, I need:
1. Set a lifecycle label to a cloneSet and Pods like foo.io/handler: "true".
2. Update images in the cloneSet.
3. Lifecycle state label in the Pod is changed to BeforeUpdate. Then I remote the handler label.
4. The CloneSet patches the Pod.

This pre-update hook helps me in data-dependency cases.
