### ISSUE TITLE
错误日志

### ISSUE THREAD

**Issue by swift201905** [openkruise/kruise#315]
2020/07/19 14:20:46 http: TLS handshake error from 10.244.0.1:56888: EOF   manager的日志，如何通信的？

**Comment by FillZpp** [comment]
@swift201905 This is caused by the readinessProbe in kruise-controller-manager pod: 

```yaml
apiVersion: v1
kind: Pod
  spec:
    # ...
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 9876
```

So kubelet will keep connecting kruise with webhook port 9876.
And when a https server is connected by tcp, it will print log TLS handshake error. It is just a warning log.

Duplicate of #280 , we should add a /healthz endpoint for healthchecking.
