### ISSUE TITLE
[BUG] CloneSet update not expected

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#316]
**What happened**:
Create a cloneset with replicas 1, and updateStrategy as follows:  
```
updateStrategy:
    maxSurge: 50%
    maxUnavailable: 10%
    partition: 0
    type: ReCreate
```
doing an update, it will delete and create new pod at the same time.

**What you expected to happen**:
After the newly pod ready，delete the old pod.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: master
- Kubernetes version (use `kubectl version`): 1.17.4
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
