### ISSUE TITLE
[BUG]  advanced daemondset after update of container image in daemondset still running with old image

### ISSUE THREAD

**Issue by Shareed2k** [openkruise/kruise#367]
**What happened**:
Hi, i have a question i'm trying to play with advanced daemondset surging methodology, but when i'm trying to do rolling restart i see pods that was created with kruise-controller-manager is still using old docker image, how can i update also this pods?

**What you expected to happen**:
bring all pods to same version

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      partition: 0
      rollingUpdateType: Surging
```

**Environment**:
- Kruise version: 0.6.0
- Kubernetes version (use `kubectl version`): Server = v1.16.11-gke.5, Client = v1.18.5
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`): 5.3.0-1016-gke
- Install tools: Helm
