### ISSUE TITLE
[BUG] Container Spec with securityContext as privileged is not working

### ISSUE THREAD

**Issue by rishi-anand** [openkruise/kruise#409]
**What happened**:
Container Spec with securityContext as privileged is not working. I have tried BroadcastJob and it was failing with below error msg.
```
rishi@Spectro$ k apply -f /Users/rishi/work/src/spectro-node-agent/broadcast-job-manifest.yaml
secret/spectro-common-dev-image-pull-secret unchanged
Error from server: error when creating "/Users/rishi/work/src/spectro-node-agent/broadcast-job-manifest.yaml": admission webhook "vbroadcastjob.kb.io" denied the request: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
```
However, it works with native Deployment, DaemonSet.

**What you expected to happen**:
I should be able to create BroadcastJob with securityContext as privileged.

**How to reproduce it (as minimally and precisely as possible)**:
Apply below manifest to reproduce it.
```
apiVersion: apps.kruise.io/v1alpha1
kind: BroadcastJob
metadata:
  name: broadcastjob-active-deadline
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: busybox
          command: ["sleep",  "50000"]
          securityContext:
            privileged: true
      restartPolicy: Never
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 10
```

**Anything else we need to know?**:
I was debugging the issue and somehow capabilities doesn't seem to be initialized properly.
https://github.com/openkruise/kruise/blob/cde3bc321b1769c770d52f793a235336ea4f549b/vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go#L5477-L5481

https://github.com/openkruise/kruise/blob/master/vendor/k8s.io/kubernetes/pkg/capabilities/capabilities.go#L83-L85

**Environment**:
- Kruise version: 0.6.0
- Kubernetes version (use `kubectl version`): v1.18.4
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`): Darwin Spectro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
- Install tools:
- Others:
