### ISSUE TITLE
[BUG] Increasing the partition in CloneSet has no effect

### ISSUE THREAD

**Issue by maxking** [openkruise/kruise#410]
**What happened**:
In a given CloneSet resource, if decrease the number of partitions by 1, one of the Pod running previous version if killed and the new one is created. However, the process does not go in reverse if I decrease the partition by 1. There is no effect of increasing the partition actually. 

**What you expected to happen**:
It should be possible to scale down new version and slowly increase the previous version when the partition is increased. If this is a feature that isn't supported, I'd expect the request to be rejected by the API.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new cloneset:
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.18.0-alpine
```
Then, update the Spec to a new image version and include partition:

```
   spec:
      containers:
      - name: nginx
        image: nginx:1.18.1-alpine
    updateStrategy:
      partition: 2
```

Then finally, update the partition value to 4:
```
updateStrategy:
  partition: 4
```

One the last update, you will see no changes in the Pods. The Update Strategy is default, `ReCreate` which makes me think it should be stopping two Pods and starting two new Pods.

**Anything else we need to know?**:
While I am running a slightly older than the latest version of Kruise, I don't see anything related to this in changelog. If this is fixed in a newer version, please let me know and I can try it out.

**Environment**:
- Kruise version: v0.5.0
- Kubernetes version (use `kubectl version`):  `v1.16.4`
- OS (e.g: `cat /etc/os-release`): `Debian GNU/Linux 9 (stretch)`
- Kernel (e.g. `uname -a`): `Linux nginx-deployment-8d9f7c4f-78wjn 4.15.0-1077-azure #82-Ubuntu SMP Thu Mar 26 03:25:09 UTC 2020 x86_64 GNU/Linux`
- Install tools: Helm 
- Others:

**Comment by Fei-Guo** [comment]
I believe Cloneset somehow wants to be consistent with upstream statefulset behavior of handling partition increase: the controller will not recreate the Pods with old version but if the Pods with ordinals that are smaller than partition are deleted, they are recreated using the old version.  

I don't see a strong use case of implementing reverting some Pods to old version when partition increases in cloneset. In typical canary release scenario, if the new version indeed has some problems, the correct remediation is to revert cloneset spec to old version instead of increasing partition.

**Comment by maxking** [comment]
I guess the explanation for the behavior is reasonable. However, the issue is that Kruise accepts the change and applies to the resource but doesn't take an action. This makes the view of the object in-consistent where I see that Partition value is 4 but there are 2 old versions running instead of 4.

Then, when you bump the version of the image, you end up in a very weird situation where you have three versions running.

Here is the sample spec (for brevity, I'll skip some boilerplate):
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0-alpine
```
After this is applied:
```
$ kubectl get pods -lapp=sample -o go-template --template='{{range .items}}{{range .spec.containers}}{{printf "%s \n" .image}} {{end}}{{end}}'
nginx:1.19.0-alpine
 nginx:1.19.0-alpine
 nginx:1.19.0-alpine
 nginx:1.19.0-alpine
 nginx:1.19.0-alpine
```
Now, I bump the version to 1.19.1 and partition to 2:
```
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.1-alpine
  updateStrategy:
    partition: 2
```
After applying it:
```
kubectl get pods -lapp=sample -o go-template --template='{{range .items}}{{range .spec.containers}}{{printf "%s \n" .image}} {{end}}{{end}}'
nginx:1.19.0-alpine
 nginx:1.19.1-alpine
 nginx:1.19.1-alpine
 nginx:1.19.0-alpine
 nginx:1.19.1-alpine
```
Everything is good until this point. I have 2 old pods and 3 new pods.

Now, at 3rd step I update the partition to 4:
```
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.1-alpine
  updateStrategy:
    partition: 4
```
And this has no effect on the pods:
```
$ kubectl get pods -lapp=sample -o go-template --template='{{range .items}}{{range .spec.containers}}{{printf "%s \n" .image}} {{end}}{{end}}'
nginx:1.19.0-alpine
 nginx:1.19.1-alpine
 nginx:1.19.1-alpine
 nginx:1.19.0-alpine
 nginx:1.19.1-alpine
```
But if you look at the resource:
```
$ kubectl describe cloneset sample
<snip>
  Update Strategy:
    Max Surge:        0
    Max Unavailable:  20%
    Partition:        4
    Type:             ReCreate
Status:
  Available Replicas:      5
  Collision Count:         0
  Label Selector:          app=sample
  Observed Generation:     3
  Ready Replicas:          5
  Replicas:                5
  Update Revision:         sample-cf8c64865
  Updated Ready Replicas:  3
  Updated Replicas:        3
```
This has Parition's value of 4, which is incorrect. It also says `Updated ready Replicas` and `Updated Replicas` is 3, which is inconsistent with the value of partition since total is 5.

Now, if I simply update the Image in next step:
```
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2-alpine
  updateStrategy:
    partition: 4
```
And apply this:
```
$ kubectl get pods -lapp=sample -o go-template --template='{{range .items}}{{range .spec.containers}}{{printf "%s \n" .image}} {{end}}{{end}}'
nginx:1.19.0-alpine
 nginx:1.19.2-alpine
 nginx:1.19.1-alpine
 nginx:1.19.1-alpine
 nginx:1.19.0-alpine
``` 
I end up in a place I don't even understand how it got to. The state of the object also doesn't reflect the state of the cluster:
```
  Update Strategy:
    Max Surge:        0
    Max Unavailable:  20%
    Partition:        4
    Type:             ReCreate
Status:
  Available Replicas:      5
  Collision Count:         0
  Label Selector:          app=sample
  Observed Generation:     4
  Ready Replicas:          5
  Replicas:                5
  Update Revision:         sample-85ff879c8b
  Updated Ready Replicas:  1
  Updated Replicas:        1
```
The partition of 4 should mean 4 of previous revision of Podspec, but it is running two of the previous spec and two from 2nd last.

**Comment by Fei-Guo** [comment]
I understand your concern. I think your experiments are more easily understandable if partition defines the number of Pods with new version. However, if partition is defined that way, it creates other problems such as every cloneset version update requires changing the partition as well even if canary release is not needed. Also, if cloneset needs to be scaled up while doing upgrade, the field `replica` and `partition` need to be adjusted at the same time. 

Note that upstream statefulset persists ordinal index in the Pod name, hence partition in fact only means `all Pods with an ordinal that is greater than or equal to the partition will be updated when the StatefulSet's .spec.template is updated.`. If you repeat your experiment with upstream statefulset, you will observe very similar behavior. 

One problem that I can see is that our API definition may cause confusion although we have tried to be as accurate as possible.  We said `Partition is the desired number of pods in old revision(S)' to cover the scenarios of having multiple old versions. We can consider removing this sentence if it is indeed causing confusion. The exact means of `partition` is described by the second sentence. 

```
        // Partition is the desired number of pods in old revisions. It means when partition
	// is set during pods updating, (replicas - partition) number of pods will be updated.
	// Default value is 0.
````

**Comment by maxking** [comment]
> I think your experiments are more easily understandable if partition defines the number of Pods with new version.
Well, I understand that part of the doc that it specifies the total number of old pods. I think your point about the ordinal of the Pod makes absolute sense from an implementation standpoint too.

Perhaps, `partition` is working as designed and this isn't really a bug. My previous understanding was that `partition` splits the Pods in only two versions. 

However, from a declarative system like Kuberentes, this seems like a lot of imperative behavior going on where the declared state doesn't give you the full picture of what the cluster's end state is going to be. A lot depends on the previous state of the cluster and can quickly get confusing with multiple old versions running. It obviously may or may not happen depending on the operations, like if you don't bump `partition` you probably won't notice what I noticed.

**Comment by Fei-Guo** [comment]
I think #411 and #413 are valid requests to better present the partition behavior as people use cloneSet.  You are correct that cloneset was initially designed to be a replacement of deployment. The concept of partition was missing in deployment and it is more difficult to explain since cloneset does not persist ordinal index in Pod. 

Besides #411 and #413, we can leverage this issue to improve document if necessary. Do you have a better proposal in mind to explain cloneset `partition` ?  You can file a PR to fix it if a proper wording helps.

**Comment by FillZpp** [comment]
Actually, workloads like CloneSet, usually they can only update Pods with the latest template defined in their spec.

For example, a CloneSet with `replicas=10`, the original revision is `v1`. First you set `partition=5` and update to revision `v2`, then you set `partition=8` and update to revision `v3`. At this moment, all Pods might stay 5 * v1, 3 * v2, 2 * v3 (also there are other conditions).

At this moment, which version do you expect CloneSet to rollback if you modify `partition` from 8 to 10? Also, both `v1` and `v2` templates are only stored in `ControllerRevisions` which are only used for record instread of using them to update Pods again.

**Comment by maxking** [comment]
Fei-Guo commented:
>  You can file a PR to fix it if a proper wording helps.

Sure, I can take stab at clarifying the current behavior of partition in the docs. I'll open a PR.

 FillZpp commented:
>  they can only update Pods with the latest template defined in their spec.

Is this because of the current implementation or some sort of limitation that cannot be changed? I see that when a Pod running old revision dies they are spinned off with the same revision. Could we not do the same when partition is increased?

> At this moment, which version do you expect CloneSet to rollback if you modify partition from 8 to 10?

Not knowing what I learned in this thread, I would expect it to go back to v1 ("stable" release IMO), which in end-state would be equivalent to `partition=0` and image version set to v1. But knowing that the behavior of Cloneset is to update the Pod based on `ordinal > partition`, I understand how we get to `5 * v1, 3 * v2, 2 * v3`.

But you see how you have to aware that the current state of the cluster is `5*v1` and `5*v2` and their respective ordinals to predict that end state of the cluster would be `5 * v1, 3 * v2 and 2 * v3` if you apply partition=5 with v3? If the ordinals were a bit different, the situation could also be  `5 * v2, 3 * v1, 2 * v3` (assuming a situation where v2 was deployed before v1 for whatever reason so current state is still 5 each of v1 & v2), so it also depends on the historical operations done on the object. I hope I am stating some real situations and not impossible/unlikely hypotheticals?

---

This would perhaps be an API change, but if you are open to it, I would instead propose that we make partition a more declarative feature instead of dependent on ordinal of the Pod like it is today or in StatefulSet. So you could declare something like this:
```
# Optionally specify revision or revision_hash or rename to controller-revision-hash for matching label name.
partition:
    revision: 3
    revision_hash: sample2-559949f8fb
    count: 80%/4
```
And this would explicitly mean that no matter what the latest Pod spec and replicas is, there would always be 4 (assuming replicas is 5) or 80% of replicas are running with revision 3 that I can look up in controllerrevisions. 

A very nice side-effect of this API is also that I am able to manage the life cycle of my Canary version & Stable version independently. So I can canary test v4 while stable is still running v1. I can also now bump my stable to v2 keeping canary at v4. This kind of control is really impossible in current API unless you carefully drive the CloneSet imperatively to end up in a situation where ordinals align correctly. This makes it a *really* flexible and a more declarative API IMO.
