### ISSUE TITLE
[BUG] Better document the behavior of partition feature in CloneSet

### ISSUE THREAD

**Issue by maxking** [openkruise/kruise#412]
**What happened**:
This is more of question and perhaps request to refine the docs than a bug report.

The documentation of `partition` in docs currently state:
> Partition is the desired number of Pods in old revisions, defaults to 0

However, it is un-clear what it considers as the "old revisions". For example:

I start with this spec:
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0-alpine
```

Then I update the partition to 2 and bump the image version:
```
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2-alpine
  updateStrategy:
    partition: 2
```
It updates the revision hash to a new value:
```
$ kubectl get pods -lapp=sample2 -L controller-revision-hash
NAME            READY   STATUS    RESTARTS   AGE     CONTROLLER-REVISION-HASH
sample2-2wxgh   1/1     Running   0          2m55s   sample2-7ccb6dfd7f
sample2-6hcb6   1/1     Running   0          2m3s    sample2-559949f8fb
sample2-crh95   1/1     Running   0          92s     sample2-559949f8fb
sample2-wjnzl   1/1     Running   0          2m55s   sample2-7ccb6dfd7f
sample2-wxtnf   1/1     Running   0          89s     sample2-559949f8fb
```
At this point, I I think `sample2-7ccb6dfd7f` is the "old revision" (1st gen) and "sample2-559949f8fb" (2nd gen) is the new revision.

(off topic: While hash is great to keep track of metadata hash internally, hash in revisions makes it extremely difficult to decide on the generation. An incremental number like in Deployment would have been really awesome, perhaps something like <name>-<generation>-<hash> would help?)

At this point, if I bump the version again and keep the partition's value same:
```
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.3-alpine
  updateStrategy:
    partition: 2
```
I end up with this:
```
$ kubectl get pods -lapp=sample2 -L controller-revision-hash
NAME            READY   STATUS    RESTARTS   AGE     CONTROLLER-REVISION-HASH
sample2-2wxgh   1/1     Running   0          4m22s   sample2-7ccb6dfd7f
sample2-4g9kd   1/1     Running   0          15s     sample2-656fc7bfbf
sample2-rt6zg   1/1     Running   0          25s     sample2-656fc7bfbf
sample2-sz7cx   1/1     Running   0          29s     sample2-656fc7bfbf
sample2-wjnzl   1/1     Running   0          4m22s   sample2-7ccb6dfd7f
```
So, it seems like at this point, the hash from the 2nd generation is gone and we only have generation 1 and generation 3 (sample2-656fc7bfbf). 

I don't fully understand what is happening here. Shouldn't 2nd generation be the "old revision"?

From an application lifecycle perspective, I guess as soon as you provide `partition`'s value to be `> 0`, CloneSet assumes that the revisions are for canary versions and does not count as the "old revision" if you keep bumping the image versions. In the above example, it seems that it designates internally that gen 1 is stable and gen 2 and gen 3 are canary releases so when version is bumped to gen 3, it keeps the "latest stable" and "latest canary" versions.

However, if you increase the `partition` number from 2 to 3:

```
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.4-alpine
  updateStrategy:
    partition: 3
```
Instead of having 2 Pods from Gen 4 and 3 Pods from Gen 1  (like I would expect given the above behavior), it has this weird:
```
$ kubectl get pods -lapp=sample2 -L controller-revision-hash
NAME            READY   STATUS         RESTARTS   AGE     CONTROLLER-REVISION-HASH
sample2-2lqpw   1/1     Running        0          9m10s   sample2-7ccb6dfd7f
sample2-2nsjp   1/1     Running        0          9m10s   sample2-7ccb6dfd7f
sample2-52td9   1/1     Running        0          4m48s   sample2-656fc7bfbf
sample2-lhpwq   0/1     ErrImagePull   0          14s     sample2-76f8bcfc66
sample2-qvzdt   1/1     Running        0          4m51s   sample2-656fc7bfbf
```
(Ignore the non-existent image pull error, should be irrelevant to discussion).

I have 1 Pod from Gen 4 (sample2-76f8bcfc66), 2 Pod from Gen 3 and 2 Pods from Gen 1.

It is really hard to understand what exactly is going on here? How does Kruise determine how many to update and which ones update and what is the "Old Version(s)".

**How to reproduce it (as minimally and precisely as possible)**:
Hopefully the above descriptions are helpful in reproducing the issue.

**Anything else we need to know?**:

**Environment**:
- Kruise version: v0.5.0
- Kubernetes version (use `kubectl version`): v1.16.4
- OS (e.g: `cat /etc/os-release`): Debian 9
- Kernel (e.g. `uname -a`): Linux nginx-deployment-8d9f7c4f-78wjn 4.15.0-1077-azure #82-Ubuntu SMP Thu Mar 26 03:25:09 UTC 2020 x86_64 GNU/Linux
- Install tools: Helm
- Others: None
