### ISSUE TITLE
[BUG] inplace update lifecycle does not work correct

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#528]
**What happened**:
create a cloneset as follows:
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: web
spec:
  lifecycle:
    inPlaceUpdate:
      labelsHandler:
        foo-unready-block: "true"
        test-unready-block: "true"
  updateStrategy:
    maxUnavailable: 1
    partition: 0
    type: InPlaceIfPossible
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        foo-unready-block: "true"
        test-unready-block: "true"
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
```
And then just update the cloneset image to make it inplace update, it will cause one pod state change to PreparingUpdate, then update the pod's label  foo-unready-block to false, it will keep PreparingUpdate state. Then update the pod's label  test-unready-block to false, the pod state will changed to Updating and start inplace update. When inplace update done, the pod state will changed to Updated. Then when I just change the pod label  foo-unready-block to true. The pod will changed to Normal state. And another pod will changed to PreparingUpdate state.

**What you expected to happen**:
Pod from Updated to Normal state, it should  satified all the hook.
 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
