### ISSUE TITLE
[BUG] NodeImage reports error the node could not be patched

### ISSUE THREAD

**Issue by Tobewont** [openkruise/kruise#553]
**What happened**:

After installing Kruise, trying to pull the image using NodeImage is wrong:

```bash
kubectl get nodeimage

NAME     DESIRED   PULLING   SUCCEED   FAILED   AGE
master   0         0         0         0        4h7m
node1    0         0         0         0        4h7m
node2    0         0         0         0        4h7m
node3    0         0         0         0        4h7m
```

```bash
kubectl edit nodeimage node1

error: nodeimages.apps.kruise.io "node1" could not be patched: Timeout: request did not complete within requested timeout 34s
You can run `kubectl replace -f /tmp/kubectl-edit-lx4rt.yaml` to try this update again.
```

What I actually edited was:

```yaml
spec: 
  images:
    ubuntu:
      tags:
      - tag: latest
        pullPolicy:
          ttlSecondsAfterFinished: 300
          timeoutSeconds: 600
          backoffLimit: 3
          activeDeadlineSeconds: 1200
```

Modified `images` and `tags` still report this error. What does this error mean? How to solve it?

**Environment**:
- Kruise version: v0.8.0
- Kubernetes version (use `kubectl version`): v1.18.3
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7
- Install tools: helm v3.5.2
