### ISSUE TITLE
[BUG] potential problems in sidecarset

### ISSUE THREAD

**Issue by dylandee** [openkruise/kruise#565]
Hi @zmberg @FillZpp 

I am very interested in Feature 'SidecarSet'. In the process of  viewing the source code, I found two possible issues which can be easily reproduced：

  1. We all know that init containers in pod are executed in order, but Sidecarset sorts init containers by name, which would disrupt our established order.

  2. If we set main container's name as the same as the container name in Sidecarset, main container would be replaced by sidecar container in pod, which would cause some unexpected errors.

Please check if these two issues exsit. If so, I am willing to fix them ~

**Comment by zmberg** [comment]
Thank you very much for your interest in openkruise, here are the answers to the two issues above:
1. init containers order
The current solution, firstly, puts the initContainers in Sidecarset behind the initContainer defined in pod. Second, for the scenario that the same pod matches multiple SidecarSet initContainers, only the sidecarSet initContainers are sorted by name. The initContainers defined in the POD remain unchanged.
This proposal has reference issue: https://github.com/openkruise/kruise/issues/366. Do you have better idea?
2. container name conflict
Firstly, main container wouldn't be replaced by sidecar container. Because SidecarSet webhook will append sidecar containers into pod.spec.containers. But, the pod will fail to be created because of the conflict between the main container and the sidecar name. The creation of pod and sidecarSet is done separately, so there is no guarantee that the names will not conflict by k8s webhook validate.

**Comment by dylandee** [comment]
> container name conflict

I got two yamls:


```[root@node30 ~]# cat sidecarset-test.yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sidecarset-test
spec:
  selector:
    matchLabels:
      app: test
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 10%
  containers:
  - name: sidecarset-container
    image: nginx:1.14.2
    command:
    - /bin/sh
    - -c
    - sleep 1111
```
```[root@node30 ~]# cat sidecarset-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: test-pod
spec:
  containers:
  - name: sidecarset-container
    image: nginx:1.16.0
    command: ["/bin/sh"]
    args: ["-c", "sleep 3333"]
```

 i apply two yamls in order, pod is created successfully, and container in pod is from sidecarset 


```
[root@node30 ~]# kpodns  |grep test-pod
default         test-pod                                     1/1     Running            0          3m14s   172.17.0.12   node30   <none>           <none>
[root@node30 ~]# k describe pod test-pod|grep -i image
              kruise.io/sidecarset-hash-without-image:
    Image:         nginx:1.14.2
    Image ID:      docker-pullable://nginx@sha256:f7988fb6c02e0ce69257d9bd9cf37ae20a60f1df7563c3a2a6abe24160306b8d
  Normal  Pulled     25s        kubelet, node30    Container image "nginx:1.14.2" already present on machine
[root@node30 ~]#

```

**Comment by dylandee** [comment]
Yep, #366 is exactly what i mean. And I think It seems redundant to sort initcontainers in mutating webhook to build pod.

**Comment by zmberg** [comment]
@dylandee about **container name conflict**
You are right, there is a scenario of injecting sidecar when updating pods inside Ali Group. I will fix the issue, because when creating pods, it must not allow the case of sidecar and main container name conflict.

**Comment by zmberg** [comment]
@dylandee > "It seems redundant to sort initcontainers in mutating webhook to build pod"

There is two SidecarSets matched one pod.
First SidecarSet:
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sidecarset-istio
spec:
  selector:
    matchLabels:
      app: test
  initContainers:
  # Set istio proxy iptables
  - name: istio-init
     image: istio/proxyv2:1.6.8
```
Second SidecarSet:
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sidecarset-db-auth
spec:
  selector:
    matchLabels:
      app: test
  initContainers:
  # Report IP and complete DB whitelist authorization
  - name: init-db-auth
     image: webserver/db-auth:1.0.0
```
DB whitelist authorization must be executed before istio proxy setting, how to achieve?
