### ISSUE TITLE
Kill pod after broadcast job terminates

### ISSUE THREAD

**Issue by Daxcor69** [openkruise/kruise#566]
I have a bj that has this 👍 
```  
completionPolicy:
    type: Always
```

The job terminates, successfully.  In order to run the job again, I have to first delete the old pod from the cluster. I would like the option to be able to kill the pod as well after the job has completed.  I don't want it hanging around.

thanks
Brad

**Comment by Fei-Guo** [comment]
The Pods created by the BroadcastJob should have ownerreference being set to the Job CR. So if you delete the Job, the Pods should be deleted as well. Can you check why the Pods are not deleted?

**Comment by Daxcor69** [comment]
```
nodeuser@nyc1-www:/mnt/_code/kubernetes_setup/kruse-io$ kubectl describe pod -n default  broadcastjob-node-update-mbvjr
Name:         broadcastjob-node-update-mbvjr
Namespace:    default
Priority:     0
Node:         pool-admin-8c4j6/10.116.16.8
Start Time:   Tue, 23 Mar 2021 15:22:26 -0700
Labels:       broadcastjob-controller-uid=fe0eb57a-0a56-4456-bba0-5ef64eb7dd40
              broadcastjob-name=broadcastjob-node-update
Annotations:  <none>
Status:       Succeeded
IP:           10.244.3.95
IPs:
  IP:           10.244.3.95
Controlled By:  BroadcastJob/broadcastjob-node-update
Containers:
  core:
    Container ID:  containerd://1b99edd66aaf3a71e3d40032cc55f26241f9cb69e4d6f3e2adc206268a8bafe0
    Image:         netroby/alpine-rsync
    Image ID:      docker.io/netroby/alpine-rsync@sha256:1dcbcf998b164408a03845e93a2697dc8d4f9b405489c11681f1d9ac1f7a2f8b
    Port:          <none>
    Host Port:     <none>
    Command:
      /scripts/copy.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 23 Mar 2021 15:22:27 -0700
      Finished:     Tue, 23 Mar 2021 15:26:41 -0700
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /core from coredir (rw)
      /mnt/core from nfscoredir (rw)
      /scripts from nodecopy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6xpqn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  nfscoredir:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    10.116.16.2
    Path:      /mnt/dry_app
    ReadOnly:  false
  coredir:
    Type:          HostPath (bare host directory volume)
    Path:          /core
    HostPathType:
  nodecopy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      nodecopy
    Optional:  false
  default-token-6xpqn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6xpqn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  12m   default-scheduler  Successfully assigned default/broadcastjob-node-update-mbvjr to pool-admin-8c4j6
  Normal  Pulling    12m   kubelet            Pulling image "netroby/alpine-rsync"
  Normal  Pulled     12m   kubelet            Successfully pulled image "netroby/alpine-rsync" in 162.313491ms
  Normal  Created    12m   kubelet            Created container core
  Normal  Started    12m   kubelet            Started container core
```

so here is what describe, shows. Here is my yaml.

```
apiVersion: apps.kruise.io/v1alpha1
kind: BroadcastJob
metadata:
  name: broadcastjob-node-update
  namespace: default
spec:
  template:
    spec:
      volumes:
        - name: nfscoredir
          nfs:
            server: 10.116.16.2
            path: /mnt/foundry_app
        - name: coredir
          hostPath:
            path: /foundrycore
        - name: nodecopy
          configMap:
            name: nodecopy
            defaultMode: 511
      containers:
        - name: core
          image: netroby/alpine-rsync
          command: ['/scripts/copy.sh']
          volumeMounts:
            - name: nfscoredir
              mountPath: /mnt/foundrycore
            - name: coredir
              mountPath: /foundrycore
            - name: nodecopy
              mountPath: /scripts
      restartPolicy: Never
  completionPolicy:
    type: Always
```
the script that runs in the pod
```
#!/bin/sh
    sleep 50
    rsync -a --delete /mnt/core /
```
