### ISSUE TITLE
[BUG] broadcastJob reconcile failed

### ISSUE THREAD

**Issue by hantmac** [openkruise/kruise#582]
**What happened**:
I create a `broadcatJob` use next yaml:

```
apiVersion: apps.kruise.io/v1alpha1
kind: BroadcastJob
metadata:
  name: broadcastjob-ttl
spec:
  parallelism: 2
  template:
    spec:
      tolerations:
       - effect: NoSchedule
         key: reserved
         operator: Equal
         value: cd-staging
      containers:
        - name: pi
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  completionPolicy:
    type: Always
    ttlSecondsAfterFinished: 10
```
BUT, the `broadcastJob` stop in the next status:

![image](https://user-images.githubusercontent.com/7600925/113480276-1e6fa200-94c6-11eb-968a-d11b648dddc1.png)
 

**What you expected to happen**:

I want the `bcj` run until all the job (number of node) completed.

**How to reproduce it (as minimally and precisely as possible)**:

Use the yaml above to create a bcj.

**Anything else we need to know?**:

**Environment**:  k8s 1.18
- Kruise version: v0.8.0
- Kubernetes version (use `kubectl version`): 1.18

The I use source to debug it, I found a bug in https://github.com/openkruise/kruise/blob/6dae2c5d348c53332bafb5249864b2ffbcf43c06/pkg/controller/broadcastjob/broadcastjob_controller.go#L163 , every time I start the controllers, then creating a new bcj, the `broadcast controller` only make sense once and It's blocked on that line of code , 
![image](https://user-images.githubusercontent.com/7600925/113480590-97bbc480-94c7-11eb-8f1b-bfbc531e9d09.png)

because  in code `scaleSatisfied, unsatisfiedDuration, scaleDirtyPods :=scaleExpectations.SatisfiedExpectations(request.String());` the `scaleSatisfied` always be false, so the reconcile cannot continue  .

If i comment that code, all things ok, so I have a question, why broadcastJob need `SatisfiedExpectations` ?
