### ISSUE TITLE
[BUG] create sidecarSet with volumes.downwardAPI failed

### ISSUE THREAD

**Issue by zmberg** [openkruise/kruise#597]
create sidecarSet with volumes.downwardAPI failed.
sidecarSet.yaml
```
# sidecarset.yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  containers:
  - name: sidecar1
    image: centos:6.7
    command: ["sleep", "999d"] # do nothing at all
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
```
kubectl create -f sidecarset.yaml
Error from server: error when creating "sidecarset.yaml": admission webhook "vsidecarset.kb.io" denied the request: [spec.volumes[0].downwardAPI.fieldRef.apiVersion: Required value, spec.containers[0].volumeMounts[0].name: Not found: "podinfo"]
