### ISSUE TITLE
Documentation may not match behavior

### ISSUE THREAD

**Issue by murrayres** [openkruise/kruise#627]
Documentation states that with Surging type AdvancedDaemonset  changes pods by "creating the new pod and then killing the old one."  The rollout restart command is not available for this Advanced Daemonset.  When I use the patch method mentioned in another issue report, the pods restart, it puts one into Terminating phase first.  This seems to not act as expected. 

**What you expected to happen**:
I expected new pod to start up before killing the old one as documented.

**How to reproduce it (as minimally and precisely as possible)**:
```
  updateStrategy:
    rollingUpdate:
      type: Surging
      maxSurge: 5 //have tried this with percentages as well
    type: RollingUpdate
```
Create AdvanceDaemonset.  

```
kubectl -n test patch daemonset.apps.kruise.io/ds-name  --type merge --patch '{"spec":{"template":{"metadata":{"labels":{"date":"'$(date +%s)'"}}}}}'
```

Old pods are Terminated before new pods are created.

**Environment**:
- Kruise version: kruise-0.9.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

 Kernel Version:             3.10.0-1160.15.2.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://19.3.11
 Kubelet Version:            v1.18.18
 Kube-Proxy Version:         v1.18.18

**Comment by FillZpp** [comment]
@murrayres Sorry, it seems the field should be `rollingUpdateType` instead of `type`. Would you please test it again?

```yaml
  updateStrategy:
    rollingUpdate:
      rollingUpdateType: Surging
      maxSurge: 5 //have tried this with percentages as well
    type: RollingUpdate
```

I will fix the documentation soon, thanks for reporting!
