### ISSUE TITLE
[BUG] inplace update process will be hang up when the image id is not changed

### ISSUE THREAD

**Issue by wdwangcumt** [openkruise/kruise#635]
**What happened**:

First, create a cloneset `sample` by using the following yaml content:
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
  updateStrategy:
    partition: 3  --- !!! equal to the replicas !!!
    type: InPlaceOnly
```
apply it, watch the pods by command `kubectl get pod  -L controller-revision-hash -L lifecycle.apps.kruise.io/state -w`, it will work well.

Then, we edit the cloneset `sample`, modify the following fields:
```
spec:
  replicas: 3
  ...
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: nginx-copy:1.18   --- !!! change it to a new image tag, but with the same image id with the old !!!
        ...
  updateStrategy:
    ...
    partition: 1 --- !!! change it from 3 to 1 !!!
    ...
```
Watch pods, we will see the problem: 
1. **Only one pod's revision will changed, while two pods' revision changed is expected by the meaning of the `updateStrategy.partition`, and the  update process will hung up.**
```
# Outputs below are the results after 5 minutes

% kubectl get pod  -L controller-revision-hash -L lifecycle.apps.kruise.io/state -w
NAME           READY   STATUS    RESTARTS   AGE   CONTROLLER-REVISION-HASH   STATE
sample-7jrpp   1/1     Running   1          5m   sample-648847746c          Updating   --- !!! continues to be Updating !!!
sample-cgsr6   1/1     Running   0          5m   sample-7f4d7465f8          Normal
sample-vzbpx   1/1     Running   0          5m   sample-7f4d7465f8          Normal
```

2. The label `lifecycle.apps.kruise.io/state`'s value continues to be `Updating` for the pod which revision changed.
3. The status of cloneset `sample` is:
```
status:
  availableReplicas: 2
  collisionCount: 0
  currentRevision: sample-7f4d7465f8
  labelSelector: app=sample
  observedGeneration: 2
  readyReplicas: 2
  replicas: 3
  updateRevision: sample-648847746c
  updatedReadyReplicas: 0  --- !!! continues to be 0 !!!
  updatedReplicas: 1   --- !!! continues to be 1 !!!
```

**What you expected to happen**:

Two pods' revision changed, and the status of cloneset and pods should be normal.

**How to reproduce it (as minimally and precisely as possible)**:

See the description above.

**Anything else we need to know?**:

I tried to fix this problem at https://github.com/openkruise/kruise/pull/636

**Environment**:
- Kruise version: v0.9.0 / master branch
- Kubernetes version (use `kubectl version`): v1.20.2 (installed by kind on MAC)
- OS (e.g: `cat /etc/os-release`): MAC OS
- Kernel (e.g. `uname -a`):
- Install tools: helm
- Others:
