### ISSUE TITLE
[feature request] How to choose between multiple containers control by SidecarSet?

### ISSUE THREAD

**Issue by algebra2k** [openkruise/kruise#660]
**What would you like to be added**:
In our cluster, we run deployments too many. and we want to use SidecarSet to provide automatic sidecar injection for the deployments.

Normally, the image version of our sidecar container is fixed. e.g. `image: sidecar: prod` and we add the 
```yaml
label: 
  sidecar-version: prod
```` 
to deployments allow `SidecarSet` to inject them.

However, when we have a new version of the sidecar container image (e.g. `image: sidecar: debug`) will have some problems.

We now have an API for the `SidecarSet`
```yaml
# prod: sidecar-version:prod
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: prod
spec:
  selector:
    matchLabels:
      sidecar-version: prod 
  containers:
  - name: prod-sidecar
    image: sidecar:prod
```

and we have some deployments.

```yaml
# dp1, ns1: app: dp1, version: v1, sidecar-version: prod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp1
  namespace: ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp1
  template:
    metadata:
      labels:
        app: dp1
        version: v1
        sidecar-version: prod
    spec:
     # ...
---
# dp2, ns2: app: dp2, version: v1, sidecar-version: prod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp2
  namespace: ns2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp2
  template:
    metadata:
      labels:
        app: dp2
        version: v1
        sidecar-version: prod
    spec:
     # ...
---
# dp3, ns3: app: dp3, version: v2, sidecar-version: prod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp3
  namespace: ns3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp3
  template:
    metadata:
      labels:
        app: dp3
        version: v2
        sidecar-version: prod
    spec:
     # ...
```

Now, we want to add another `SidecarSet` to the injection
```yaml
# prod: sidecar-version:prod version: v1
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: debug
spec:
  selector:
    matchLabels:
      sidecar-version: prod
      version: v2
  containers:
  - name: dehug-sidecar
    image: sidecar:debug

``` 
Deployments:

| Name  | Namespace | Labels |
| ------------- | ------------- |   ------------- |
| dp1  | ns1  |  `app: dp1` `version: v1` `sidecar-version: prod` |
| dp2  | ns2  |  `app: dp2` `version: v1` `sidecar-version: prod` |
| dp3  | ns3  |  `app: dp3` `version: v2` `sidecar-version: prod` |

SidecarSets

| Name  | Namespace | MatchLables |
| ------------- | ------------- |   ------------- |
| prod  |  |  `sidecar-version: prod` |
| debug  |  | `sidecar-version: prod` ` version: v2` |

Match Results
| Sidecar  | Deployments |
| ------------- | ------------- |
| prod | dp1, dp2, dp3|
| debug | dp3 | 

So, when I'm rolling deployment, which one should the deployment inject? ( I expect debug.)

**Why is this needed**:

I wish `SidecarSet` could provide priority, just like: 
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: prod
spec:
  selector:
    matchLabels:
      sidecar-version: prod
  containers:
  - name: prod-sidecar
    image: sidecar:prod
  priorityValue: 1
---
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: debug
spec:
  selector:
    matchLabels:
      sidecar-version: prod
      version: v2
  containers:
  - name: dehug-sidecar
    image: sidecar:debug
 priorityValue: 2
```

so that when there are multiple targets, the one with the highest priority value is selected.
