### ISSUE TITLE
[BUG] pod metadata is not validated when creating CloneSet

### ISSUE THREAD

**Issue by codwu** [openkruise/kruise#674]
**What happened**:
Create a cloneset
```
kubectl apply -f sample.yaml
```
the `sample.yaml` is below
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      foo: bar
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:latest
```
Note the pod metadata has an invalid field: `foo`. 
In fact, the cloneset is created successfully without any error.  However, the created cloneset don't have `foo` in `spec.template.metadata`.

**What you expected to happen**:
There should be an error and I cannot create the cloneset.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: 0.9.0
- Kubernetes version (use `kubectl version`): 1.19.9
- OS (e.g: `cat /etc/os-release`): centos 7
- Kernel (e.g. `uname -a`): 3.10
- Install tools:
- Others:

**Comment by FillZpp** [comment]
@codwu Currently we have no way to validate the unknown fields, because the `template` structure is so complicated that it has to be a single object in CloneSet CRD:
```
            template:
              description: Template describes the pods that will be created.
              type: object
              x-kubernetes-preserve-unknown-fields: true
```
