### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TAODEI** [openkruise/kruise#727]
**What happened**:
There is an error in the docs of [sidecarset](https://openkruise.io/en-us/docs/sidecarset.html) 
_Example/Create SidecarSet_
```yaml
# sidecarset.yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  containers:
  - name: sidecar1
    image: centos:6.7
    command: ["sleep", "999d"] # do nothing at all
    volumeMounts:
    - name: log-volume
    mountPath: /var/log
  volumes: # this field will be merged into pod.spec.volumes
  - name: log-volume
    emptyDir: {}
```
**There should be two spaces missing at the front of line 19**

Report an error:kubectl apply -f sidecarset.yaml 
output: Error from server: error when creating "sidecarset.yaml": admission webhook "vsidecarset.kb.io" denied the request: spec.containers[0].volumeMounts[0].mountPath: Required value
**What you expected to happen**:
kubectl apply -f sidecarset.yaml 
output: sidecarset.apps.kruise.io/test-sidecarset created

**Comment by veophi** [comment]
This bug is caused by an indentation error.
The commit to fix this bug has been submitted and it is expected to be corrected in the next revision.

```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  containers:
  - name: sidecar1
    image: centos:6.7
    command: ["sleep", "999d"] # do nothing at all
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes: # this field will be merged into pod.spec.volumes
  - name: log-volume
    emptyDir: {}
```
