### ISSUE TITLE
[feature request] Consider relaxing  the constraint of conflict detection condition for SidecarSet.Spec.Selector 

### ISSUE THREAD

**Issue by veophi** [openkruise/kruise#732]
**What would you like to be added**:
Relax the constraint of conflict detection condition for `spec.selector` when validating SidecarSet at webhook.

**Why is this needed**:
Now, SidecarSet requires absolute exclusive for `.spec.selector` when container name has conflict . However, for some scenarios, such as 
```
# SidecarSet1
selector:
  matchLabels:
    web: nginx
containers:
-  name: logCollector

# SidecarSet2
selector:
  matchLabels:
    db: redis
containers:
-  name: logCollector
```
these two SidecarSets will also be treated as conflict even though users can ensure these SidecarSets won't select the same Pods. This conflict detection strategy is so strict that users often have to change the names of containers. But for the scenarios where users cannot change their container names, there will be nothing they can do to create a SidecarSet.

Therefore, I think SidecarSet should provide an optional strategy to help users to handle these scenarios. 
For example, the optional strategy could look like this:
```yaml
Spec:
   config:
      conflictIfSelectorNotAbsoluteExclusive: true //default option
      # conflictIfSelectorIsSubsetOfAnother: true
```
`conflictIfSelectorNotAbsoluteExclusive` indicates the present strategy, which can filter out all possible conflicts.
`conflictIfSelectorIsSubsetOfAnother` indicates two SidecarSet are treated as conflict if and only if one selector is a subset of another. This strategy only filters out the conflicts that are bound to occur.
