### ISSUE TITLE
[feature request] support exec command in lifecycle hook

### ISSUE THREAD

**Issue by LiYiPeng-1** [openkruise/kruise#765]
**What would you like to be added**:
Can I add custom commands to lifecycle hook "inPlaceUpdate"?
just  like  this  
~~~
lifecycle:
  preStop:
    exec:
      command:
      - /bin/bash
      - /home/prestop.sh
~~~

**Why is this needed**:
before I  In-place update  a pod , I need  logoff it  from the eureka

**Comment by FillZpp** [comment]
/retitle support exec command in lifecycle hook

**Comment by FillZpp** [comment]
@LiYiPeng-1 When Kubelet updates a container in-place, it will firstly execute the preStop hook defined in the Pod container. 

So you have not to set the preStop in lifecycle hook.

**Comment by LiYiPeng-1** [comment]
@FillZpp  thanks  for  your  reply ,  but  when I test like this ，preStop  seems to be ineffective  in  CloneSet ,  but  it's  effective  in "Deployment"   
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  updateStrategy:
    type: InPlaceIfPossible
  template:
    metadata:
      labels:
        app: nginx
    spec:
      lifecycle:
        preStart:
          exec:
            command: ["bash","echo 'test'"]
        preStop:
          exec:
            command:
            - curl
            - "192.168.8.188:8888"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - 192.168.128.154
      containers:
      - name: nginx
        image: nginx

```
