### ISSUE TITLE
[BUG] ImagePullJob issue with google container registry (gcr.io)

### ISSUE THREAD

**Issue by geraldoramos** [openkruise/kruise#780]
**What happened**:
When trying to use an ImagePullJob within a *gcr.io* image (google container registry), I get a 401 (Unauthorized error)

```
Image gcr.io/xx/yy:1.0.6 anonymous pulling failed, err unexpected status code https://gcr.io/v2/xx/yy/manifests/1.0.6: 401 Unauthorized
```

**What you expected to happen**:
I expected the default service account to be able to download images from the internal repository. I also tried to create a `kruise` secret and included it in the imagePullJob definition. I've also tried to create the secret in the `kruise-system` namespace and applied the ImagePullJob under this namespace as well, but didn't work either.

```
kubectl create secret generic kruise --from-file=key.json=./mysecret.json
```

```yml
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: prepull-yy 
spec:
  image: gcr.io/xx/yy:1.0.6
  pullSecrets:
  - kruise
  parallelism: 100      # [optional] the maximal number of Nodes that pull this image at the same time, defaults to 1
  selector:
    matchExpressions:
    - key: cloud.google.com/gke-accelerator
      operator: Exists
  completionPolicy:
    type: Always                  # [optional] defaults to Always
    ttlSecondsAfterFinished: 5  # [optional] no default, only work for Alway type
  pullPolicy:                     # [optional] defaults to backoffLimit=3, timeoutSeconds=600
    backoffLimit: 3
    timeoutSeconds: 1000
```

**How to reproduce it (as minimally and precisely as possible)**:
When trying to create an ImagePullJob for any image hosted on gcr.io, this error will happen. 

**Environment**:
- Kruise version: v0.10.0
- Kubernetes version (use `kubectl version`): 1.20.10-gke.301
