### ISSUE TITLE
[BUG] pod  NodeSelectorTerms length 0 when UnitedDeployment NodeSelectorTerms is nil and subnet MatchExpressions length 0

### ISSUE THREAD

**Issue by wxyh** [openkruise/kruise#807]
**What happened**:
In UnitedDeployment, if template's NodeSelectorTerms is nil and subset NodeSelectorTerm is nil, create sub workload NodeSelectorTerms is not nil and length equal 0, pod cannot be scheduled.

**What you expected to happen**:
If subnet NodeSelectorTerm is nil or  MatchExpressions's length equal 0, don't change template NodeSelectorTerms.

**How to reproduce it (as minimally and precisely as possible)**:
Here is the UnitedDeployment example:
``` yaml
apiVersion: apps.kruise.io/v1alpha1
kind: UnitedDeployment
metadata:
  name: sample-ud
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sample
  template:
    statefulSetTemplate:
      metadata:
        labels:
          app: sample
      spec:
        selector:
          matchLabels:
            app: sample
        template:
          metadata:
            labels:
              app: sample
          spec:
            containers:
            - image: nginx:alpine
              name: nginx
  topology:
    subsets:
    - name: subset-a
      replicas: 1
```
the UnitedDeployment create statefuleset's spec
``` yaml
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sample
      apps.kruise.io/subset-name: subset-a
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample
        apps.kruise.io/controller-revision-hash: sample-ud-75654b8444
        apps.kruise.io/subset-name: subset-a
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - {}
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
pod schedule info
```
  Warning  FailedScheduling  <unknown>  default-scheduler  0/5 nodes are available: 5 node(s) didn't match node selector.
```

**Anything else we need to know?**:
If pod NodeSelectorTerms is not nil and length equal 0, pod will not be scheduled.

**Environment**:
- Kruise version: 0.10.0
- Kubernetes version (use `kubectl version`): 1.16
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
