### ISSUE TITLE
[BUG] Cloneset minReadySeconds did not take effect

### ISSUE THREAD

**Issue by moluzhui** [openkruise/kruise#826]
**What happened**:
I want to use the `minReadySeconds` parameter to set the pod update interval, as shown in the yaml file below. When I changed the image to ibmcom/pause:3.2 and `kubectl apply` again, it did not update the pod every `60` seconds

```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: cloneset-pause
  labels:
    app.kubernetes.io/name: cloneset-pause
    app.kubernetes.io/instance: cloneset-pause
spec:
  replicas: 5
  minReadySeconds: 60
  selector:
    matchLabels:
      app.kubernetes.io/name: cloneset-pause
      app.kubernetes.io/instance: cloneset-pause
  updateStrategy:
    maxSurge: 1
    maxUnavailable: 0
    partition: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloneset-pause
        app.kubernetes.io/instance: cloneset-pause
    spec:
      containers:
        - name: cloneset-pause
          image: ibmcom/pause:3.1
```
**What you expected to happen**:
My expectation is to update a pod every 60 seconds by minReadySeconds. 

Whether I'm missing the configuration or whether I misunderstood the role of `minReadySeconds` in Cloneset

I really appreciate any help with this.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: kruise v0.10.1
- Kubernetes version (use `kubectl version`): 1.18.12
- OS (e.g: `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`):
- Install tools: helm 2.17
- Others:

**Comment by FillZpp** [comment]
>  it did not update the pod every 60 seconds

@moluzhui Could you describe the unexpected condition you meet?

**Comment by moluzhui** [comment]
> > it did not update the pod every 60 seconds
> 
> @moluzhui Could you describe the unexpected condition you meet?

After applying again, the pods are recreated directly in sequence, with almost no pause
```
NAME                              READY   STATUS    RESTARTS   AGE
cloneset-pause-8tgrf              1/1     Running   0          42s
cloneset-pause-dswjw              1/1     Running   0          50s
cloneset-pause-jhc8n              1/1     Running   0          37s
cloneset-pause-m88c8              1/1     Running   0          40s
cloneset-pause-ssg7r              1/1     Running   0          47s
```

**Comment by veophi** [comment]
> > > it did not update the pod every 60 seconds
> > 
> > 
> > @moluzhui Could you describe the unexpected condition you meet?
> 
> After applying again, the pods are recreated directly in sequence, with almost no pause
> 
> ```
> NAME                              READY   STATUS    RESTARTS   AGE
> cloneset-pause-8tgrf              1/1     Running   0          42s
> cloneset-pause-dswjw              1/1     Running   0          50s
> cloneset-pause-jhc8n              1/1     Running   0          37s
> cloneset-pause-m88c8              1/1     Running   0          40s
> cloneset-pause-ssg7r              1/1     Running   0          47s
> ```

Kruise 1.0.0 has fixed this bug #763.

**Comment by FillZpp** [comment]
> After applying again, the pods are recreated directly in sequence, with almost no pause

@moluzhui It might because `minReadySeconds` is `60` but the pods just created have not ready longer than 60s.

What does it become after you wait for 1~2min?

**Comment by moluzhui** [comment]
> > After applying again, the pods are recreated directly in sequence, with almost no pause
> 
> @moluzhui It might because `minReadySeconds` is `60` but the pods just created have not ready longer than 60s.
> 
> What does it become after you wait for 1~2min?

Sorry I didn't keep it that long, but `pause container` should not have 60s still ready, which seems to work after I update 1.0.0.beta.0

**Comment by moluzhui** [comment]
> > > > it did not update the pod every 60 seconds
> > > 
> > > 
> > > @moluzhui Could you describe the unexpected condition you meet?
> > 
> > 
> > After applying again, the pods are recreated directly in sequence, with almost no pause
> > ```
> > NAME                              READY   STATUS    RESTARTS   AGE
> > cloneset-pause-8tgrf              1/1     Running   0          42s
> > cloneset-pause-dswjw              1/1     Running   0          50s
> > cloneset-pause-jhc8n              1/1     Running   0          37s
> > cloneset-pause-m88c8              1/1     Running   0          40s
> > cloneset-pause-ssg7r              1/1     Running   0          47s
> > ```
> 
> Kruise 1.0.0 has fixed this bug #763.

This doesn't seem to be appropriate for `inPlace updates`. I don't think the pod state should be `ready` during container updates. However, `minReadySeconds and readinessGates` don't seem to work for `inPlace updates` in `Cloneset`

**Comment by FillZpp** [comment]
> This doesn't seem to be appropriate for inPlace updates. I don't think the pod state should be ready during container updates. However, minReadySeconds and readinessGates don't seem to work for inPlace updates in Cloneset

Don't really understand your point. When a pod is in-place updating, kruise will make it not-ready using readinessGates as I said in #828 .

**Comment by moluzhui** [comment]
> > This doesn't seem to be appropriate for inPlace updates. I don't think the pod state should be ready during container updates. However, minReadySeconds and readinessGates don't seem to work for inPlace updates in Cloneset
> 
> Don't really understand your point. When a pod is in-place updating, kruise will make it not-ready using readinessGates as I said in #828 .

Then, how should I reflect [it](https://openkruise.io/docs/user-manuals/cloneset#in-place-update)? I deployed the following cloneset, and then `modified the image version` and `applied` it again by `kubectl apply`. I only found that the number of **RESTARTS** increased, but I did not see the Pod's **not-ready** intermediate process.
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: cloneset-pause
  labels:
    app.kubernetes.io/name: cloneset-pause
    app.kubernetes.io/instance: cloneset-pause
spec:
  replicas: 5
  # minReadySeconds: 30
  selector:
    matchLabels:
      app.kubernetes.io/name: cloneset-pause
      app.kubernetes.io/instance: cloneset-pause
  updateStrategy:
    # paused: true
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 20
    maxSurge: 1
    maxUnavailable: 0
    partition: 0
    type: InPlaceIfPossible
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloneset-pause
        app.kubernetes.io/instance: cloneset-pause
    spec:
      containers:
        - name: cloneset-pause
          image: ibmcom/pause:3.1   # to 3.2
```
the output is 
```
kubectl get pod
NAME                              READY   STATUS    RESTARTS   AGE
cloneset-pause-7vl2b              1/1     Running   1          6m20s
cloneset-pause-8nk78              1/1     Running   1          6m19s
cloneset-pause-fq69z              1/1     Running   1          6m19s
cloneset-pause-gp6t2              1/1     Running   0          5m24s
cloneset-pause-vsf87              1/1     Running   1          6m19s
```
