### ISSUE TITLE
[BUG] Cloneset supports readinessGates configuration

### ISSUE THREAD

**Issue by moluzhui** [openkruise/kruise#828]
**What would you like to be added**:
I wish **Cloneset** supported **readinessGates** configuration, as `Advanced StatefulSet` does
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: cloneset-pause
  labels:
    app.kubernetes.io/name: cloneset-pause
    app.kubernetes.io/instance: cloneset-pause
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: cloneset-pause
      app.kubernetes.io/instance: cloneset-pause
  updateStrategy:
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 20
    maxUnavailable: 3
    partition: 0
    type: InPlaceIfPossible
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloneset-pause
        app.kubernetes.io/instance: cloneset-pause
    spec:
      readinessGates:
         # A new condition that ensures the pod remains at NotReady state while the in-place update is happening
      - conditionType: InPlaceUpdateReady
      containers:
        - name: cloneset-pause
          image: dockerregister.hikops.com/k8s/pause-amd64:3.2
```

**Why is this needed**:
It triggers pod `Not Ready`, which causes the Endpoint Controller to remove the pod from the service , update the image, and finally return to Ready, ensuring that **data traffic is not lost**
