### ISSUE TITLE
[feature request] Allow definition of environment variables (and secrets) directly in the SidecarSet yaml

### ISSUE THREAD

**Issue by BryanDollery** [openkruise/kruise#838]
**What would you like to be added**:
It seems that the only way to get environment variables into a kruise sidecar is through the `transferEnv` feature. While this is a very useful feature, I would also like to be able to define environment variables directly on the sidecar, like so:

```yaml
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
```

**Why is this needed**:
My scenario is that I want my engineers to build REST services, but I want to invoke the services from events on a redis pub/sub bus, so I want to abstract the bus access out into a sidecar that takes events off the bus and passes the payload onto the main container's endpoint. When the call returns, the response is put back on the bus.

In this example, I don't want to give my main containers access to the redis password. It is only used by the sidecar and tbh the main container engineers don't need to know anything about redis, not even that it is being used. I'd rather only have the yaml that pulls the password in a single place -- the sidecar configuration. As it stands though, I have to define the redis password in every service and access it through the `transferEnv` capability.

**Comment by FillZpp** [comment]
@BryanDollery Thanks for the feedback.

Actually, SidecarSet does support it. For example:

```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
...
spec:
  containers:
  - name: sidecar
    transferEnv:
    - sourceContainerName: main
      envName: PROXY_IP  
    env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-password
          key: password
```

The `transferEnv` defines environments that should be shared from other containers in Pod, and `env` defines environments for the sidecar container itself.
