### ISSUE TITLE
[BUG]AdvancedCronJob BroadcastJob successfulJobsHistoryLimit:0 重复创建 BroadcastJob

### ISSUE THREAD

**Issue by saihide** [openkruise/kruise#862]
**What happened**:
第一种情况：  在AdvancedCronJob中配置了BroadcastJob, 设置successfulJobsHistoryLimit:0的时候，当BroadcastJob执行完成并结束(Completed),pod会立刻被删除，重复创建了一个新的BroadcastJob，如此反复循环。

第二种情况： 设置tlSecondsAfterFinished: 60，startingDeadlineSeconds: 50
当BroadcastJob执行完成并结束，过了tlSecondsAfterFinished的时间，job和pod并没有删除。

**What you expected to happen**:
任务执行完成, 垃圾回收结束, 等待下一次定时任务

**Anything else we need to know?**:
AdvancedCronJob 配置如下
第一种情况
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: AdvancedCronJob
metadata:
  name: ingresslogbackup
  namespace: ingress-nginx
spec:
  schedule: "13 9 * * *"
  successfulJobsHistoryLimit: 0
  template:
    broadcastJobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: ingresslogbackup
                imagePullPolicy: IfNotPresent
                image: f6car-registry-vpc.cn-shanghai.cr.aliyuncs.com/devops/ingresslogbackup:12171802
                env:
                  - name: POD_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                command:
                  - /bin/sh
                  - -c
                  - sh /root/ingress-logs-backup.sh
        completionPolicy:
          type: Always
```

第二种情况
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: AdvancedCronJob
metadata:
  name: ingresslogbackup
  namespace: ingress-nginx
spec:
  schedule: "49 8 * * *"
  startingDeadlineSeconds: 50
  template:
    broadcastJobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: ingresslogbackup
                imagePullPolicy: IfNotPresent
                image: f6car-registry-vpc.cn-shanghai.cr.aliyuncs.com/devops/ingresslogbackup:12171802
                command:
                  - /bin/sh
                  - -c
                  - sh /root/ingress-logs-backup.sh
        completionPolicy:
          type: Always
          tlSecondsAfterFinished: 60
```

**Environment**:
- Kruise version: v0.10.0
- Kubernetes version (use `kubectl version`): 
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7
- Kernel (e.g. `uname -a`): 3.10.0-1160.36.2.el7.x86_64
