### ISSUE TITLE
[feature request] PreDownloadImage after some number count pods  update ready

### ISSUE THREAD

**Issue by shiyan2016** [openkruise/kruise#876]
**What would you like to be added**:
CloneSet trigger PreDownloadImage after some updated pods ready.

**Why is this needed**:
If the new revision image has some problem, predownload the image for the pods for inplace update is wasteful.

**Comment by FillZpp** [comment]
Great!
@shiyan2016 Are you going to work on this? Or I can do it later.

**Comment by shiyan2016** [comment]
@FillZpp I can work on it if this is not urgent.

**Comment by voron** [comment]
I would prefer this feature to be optional

**Comment by FillZpp** [comment]
> I would prefer this feature to be optional

Yep, after the discussion in community meeting last month, we decided to add an optional annotation for users, such as:

```yaml
kind: CloneSet
metadata:
  annotations:
    apps.kruise.io/image-predownload-min-ready-pods: "5"
```

Just like the `apps.kruise.io/image-predownload-parallelism` we provided before.
