### ISSUE TITLE
[BUG] Workload spread doesn't scaledown as expected

### ISSUE THREAD

**Issue by perek** [openkruise/kruise#877]
**What happened**:
Workload spread is supposed to keep the CloneSet or Deployment pods within a set bounds based on `maxReplicas`, this appears to mostly work on scale-up, but has some behavior I would not expect on scale-down. What I would like to achieve is an even split among 2 availability zones

**What you expected to happen**:
The zones would be split up according to missingReplicas on scale-down and up

**How to reproduce it (as minimally and precisely as possible)**:
WorkflowSpread
```
apiVersion: apps.kruise.io/v1alpha1
kind: WorkloadSpread
metadata:
  name: ws-demo
  namespace: default
spec:
  targetRef: # workload in the same namespace
    apiVersion: apps.kruise.io/v1alpha1
    kind: CloneSet
    name: sample
  subsets:
  - name: us-central1-b # zone ACK
    maxReplicas: 34%
    requiredNodeSelectorTerm:
      matchExpressions:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-central1-b
    patch: # inject label.
      metadata:
        labels:
          deploy/zone: us-central1-b
  - name: us-central1-c # zone ACK
    maxReplicas: 33%
    requiredNodeSelectorTerm:
      matchExpressions:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-central1-c
    patch: # inject label.
      metadata:
        labels:
          deploy/zone: us-central1-c
  - name: us-central1-f # zone ACK
    maxReplicas: 33%
    requiredNodeSelectorTerm:
      matchExpressions:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-central1-f
    patch: # inject label.
      metadata:
        labels:
          deploy/zone: us-central1-f
```
Cloneset
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 6
  selector:
    matchLabels:
      app: sample
  updateStrategy:
    partition: 10%
  template:
    metadata:
      labels:
        app: sample
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: sample
      containers:
      - name: nginx
        image: nginx:alpine
```

Commands run:
```
pkyle@C02CV1QAMD6R Dev % kubectl get po -oyaml | grep deploy/zone | sort
      deploy/zone: us-central1-b
pkyle@C02CV1QAMD6R Dev % kubectl scale clonesets.apps.kruise.io sample --replicas=3
cloneset.apps.kruise.io/sample scaled
pkyle@C02CV1QAMD6R Dev % kubectl get po -oyaml | grep deploy/zone | sort           
      deploy/zone: us-central1-b
      deploy/zone: us-central1-b
      deploy/zone: us-central1-c
pkyle@C02CV1QAMD6R Dev % kubectl scale clonesets.apps.kruise.io sample --replicas=4
cloneset.apps.kruise.io/sample scaled
pkyle@C02CV1QAMD6R Dev % kubectl get po -oyaml | grep deploy/zone | sort           
      deploy/zone: us-central1-b
      deploy/zone: us-central1-b
      deploy/zone: us-central1-c
      deploy/zone: us-central1-c
pkyle@C02CV1QAMD6R Dev % kubectl scale clonesets.apps.kruise.io sample --replicas=5
cloneset.apps.kruise.io/sample scaled
pkyle@C02CV1QAMD6R Dev % kubectl get po -oyaml | grep deploy/zone | sort           
      deploy/zone: us-central1-b
      deploy/zone: us-central1-b
      deploy/zone: us-central1-c
      deploy/zone: us-central1-c
      deploy/zone: us-central1-f
pkyle@C02CV1QAMD6R Dev % kubectl scale clonesets.apps.kruise.io sample --replicas=6
cloneset.apps.kruise.io/sample scaled
pkyle@C02CV1QAMD6R Dev % kubectl get po -oyaml | grep deploy/zone | sort           
      deploy/zone: us-central1-b
      deploy/zone: us-central1-b
      deploy/zone: us-central1-b
      deploy/zone: us-central1-c
      deploy/zone: us-central1-c
      deploy/zone: us-central1-f
pkyle@C02CV1QAMD6R Dev % kubectl scale clonesets.apps.kruise.io sample --replicas=3
cloneset.apps.kruise.io/sample scaled
pkyle@C02CV1QAMD6R Dev % kubectl get po -oyaml | grep deploy/zone | sort           
      deploy/zone: us-central1-b
      deploy/zone: us-central1-b
      deploy/zone: us-central1-b
      deploy/zone: us-central1-c
```

If I look at the set after scaledown, why did it stick ALL the replicas in b if the missingReplicas > 0 on other subsets
```
status:
    observedGeneration: 1
    subsetStatuses:
    - missingReplicas: 0
      name: us-central1-b
      replicas: 3
    - missingReplicas: 1
      name: us-central1-c
      replicas: 0
    - missingReplicas: 1
      name: us-central1-f
      replicas: 0
````
**Anything else we need to know?**:

**Environment**:
- Kruise version: latest
- Kubernetes version (use `kubectl version`): 1.20
- Install details (e.g. helm install args): i set the workflow feat flag, thats it
- Others:
