### ISSUE TITLE
[BUG]CloneSet, pods with status of NodeAffinity should be cleaned when UpdatedReplicas==Replicas

### ISSUE THREAD

**Issue by DrAuYueng** [openkruise/kruise#925]
**What happened**:
Deploy CloneSet which specified replicas 1,  and node selector such as : 
```
nodeSelector:
  foo: "bar"
```
k8s scheduled pod with different node, eg: 192.168.0.10, 192.168.0.11
<img width="831" alt="image" src="https://user-images.githubusercontent.com/1527849/157614013-c3664014-b936-4e43-a234-f93d0abc12b7.png">

Pod status:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-09T09:45:59Z"
    status: "True"
    type: KruisePodReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-09T09:46:00Z"
    status: "True"
    type: InPlaceUpdateReady
  message: Pod Predicate NodeAffinity failed
  phase: Failed
  reason: NodeAffinity
  startTime: "2022-03-09T09:46:09Z"
```

**What you expected to happen**:
Pods with status of NodeAffinity should be cleaned when UpdatedReplicas==Replicas

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: v1.0.1
- Kubernetes version (use `kubectl version`): v1.20.15-rc.0
- Install details (e.g. helm install args): helm install kruise openkruise/kruise --version 1.0.1 --set featureGates="CloneSetPartitionRollback=true"
- Others:
