### ISSUE TITLE
[BUG] sidecarset doesn't update pods as expected.

### ISSUE THREAD

**Issue by ljun20160606** [openkruise/kruise#928]
**What happened**:

Hot upgrades are triggered when image and other container configurations are changed at the same time. It cause the image to be upgraded to the latest, but the configurations will not be updated.

**What you expected to happen**:

method UpdateSidecarSet should skip updates of pods if configuration of container changes except image.

**How to reproduce it (as minimally and precisely as possible)**:

updates sidecarset from

```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: hotupgrade-sidecarset
spec:
  selector:
    matchLabels:
      app: hotupgrade
  containers:
  - name: sidecar
    image: openkruise/hotupgrade-sample:sidecarv1
```

to

```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: hotupgrade-sidecarset
spec:
  selector:
    matchLabels:
      app: hotupgrade
  containers:
  - name: sidecar
    image: openkruise/hotupgrade-sample:sidecarv2
    env:
      - name: VERSION
        value: sidecarv2
```
