### ISSUE TITLE
[feature request]sidecarset support volume added by sidecar to main container

### ISSUE THREAD

**Issue by qixiaobo** [openkruise/kruise#939]
**What would you like to be added**:
Scenes
Support javaagent mount using init-container
accomplish
1. The initcontainer defines the specified environment variables, such as JAVA_TOOL_OPTIONS, which is expected to be injected into the environment variables. After the sidecar is defined, it is also injected into the main pod.
2. initcontainer downloads javaagent to the specified path and the main pod needs to share the volume, that is, it needs to support mounting the volume used by the sidecar in the container

**Why is this needed**:
1. Currently sidecarset has limited support for initcontainer, such as various volumes not merged. 1.1.0 has been supported
2. It is impossible to share the volume mounted on the sidecar with the main container.
3. Environment variables cannot be shared with the main container

**Comment by qixiaobo** [comment]
https://github.com/openkruise/kruise/issues/934 this fixed 
![image](https://user-images.githubusercontent.com/2881751/159663004-fd195342-22b0-4257-9220-e32b9b8ca376.png)

**Comment by qixiaobo** [comment]
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sidecarset-test
spec:
  selector:
    matchLabels:
      app: xxx
  initContainers:
    - name: init-agent-container
      image: xxxagent:xxx
      command: [ "/bin/sh", "-c", "initenv.sh" ]
      env:
        - name: XXX_AGENT_VERSION
          value: xxx
      volumeMounts:
        - name: xxx-agent-vol
          mountPath: ~/.opt/sandbox/
      addEnv:
        - targetContainerName: xxx
          envName: JAVA_TOOL_OPTIONS
          envValue: -javaagent:~/.opt/sandbox/lib/sandbox-agent.jar
      addMount:
        - targetContainerName: xxx
          name: xxx-agent-vol
          mountPath: ~/.opt/sandbox/
  updateStrategy:
    type: NotUpdate
  namespace: test
  volumes:
    - name: xxx-agent-vol
      emptyDir: { }

```

The `initenv.sh` may download the agent to specify location
We'd better support container index because the main container may not have the same name.
`addEnv` stands for add env to specify container
`addVolume` stands for add volume to specify container

Then we may use JAVA_TOOL_OPTIONS to pick up javaAgent

We can refer to
https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html
