### ISSUE TITLE
Are there plans to make the ordinal index for a statefulset available dynamically within a config file?

### ISSUE THREAD

**Issue by l-duan** [openkruise/kruise#984]
It would be good if there were some templating format so that the property could be set directly in the config file. E.g. (simplified):
```yaml
apiVersion: apps.kruise.io/v1beta1
kind: StatefulSet
metadata:
  name: zk
spec:
  serviceName: zk-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk
        imagePullPolicy: Always
        image: zookeeper
        resources:
        env:
        - name : ZOO_MY_ID
          value: ${{ordinal}}
        - name : ZOO_SERVERS
          value: server.0=zk-0:2888:3888 server.1=zk-1:2888:3888 server.2=zk-2:2888:3888
        - name : ZOO_TICK_TIME
          value: "2000"
        - name : ZOO_INIT_LIMIT
          value: "10"
        - name : ZOO_SYNC_LIMIT
          value: "5"
```
**What would you like to be added**:

**Why is this needed**:
